import "server-only";
import { cache } from "react";
import { requireArea } from "@/lib/auth";
import { createClient } from "@/lib/supabase/server";
import { contractedMrr, coverageAnalytics, monthlyAlertSeeds, type ContractRow, type GenerationRunRow, type MonthlyPeriodRow } from "@/lib/ceo-analytics-domain";

export type CeoPeriod="today"|"7"|"30";
export type CeoFilters={period:CeoPeriod;unitId:string};
export type CeoUnit={id:string;name:string;capacity:number;timezone:string;is_active:boolean};
export type CeoSession={id:string;unit_id:string;vehicle_id:string|null;plate_snapshot:string;vehicle_type:string;status:string;entered_at:string;exited_at:string|null;final_amount:number|null;calculated_amount:number|null;payment_status:string;entry_mode:string;financial_obligation:string;monthly_subscription_id:string|null;monthly_billing_period_id:string|null;monthly_coverage_reason:string|null;theoretical_amount:number|null;entry_operator_id:string;exit_operator_id:string|null};
export type CeoPayment={id:string;unit_id:string;payment_subject_type:"PARKING_SESSION"|"MONTHLY_BILLING_PERIOD";parking_session_id:string|null;monthly_billing_period_id:string|null;amount:number;gross_amount:number;fee_amount:number|null;net_amount:number|null;method:string;payment_channel:string;provider:string|null;provider_environment:string|null;operational_status:string;settlement_status:string;status:string;manual_confirmation:boolean;paid_at:string|null;created_at:string;received_by:string|null;cash_shift_id:string|null;parking_sessions:{plate_snapshot:string;entered_at:string}|null;monthly_billing_periods:{reference_year:number;reference_month:number}|null};
export type CeoShift={id:string;unit_id:string;operator_id:string;opened_at:string;closed_at:string|null;opening_amount:number;status:string;declared_cash_amount:number|null;expected_cash_amount:number|null;difference_amount:number|null;notes:string|null};
export type CeoAlert={id:string;category:"Operacional"|"Financeiro";severity:"Info"|"Atenção"|"Crítico";unitId:string;unitName:string;at:string;title:string;description:string;href:string};

const occupying=new Set(["OPEN","PAYMENT_PENDING","PAID","MANUAL_REVIEW"]);
function offsetMs(timeZone:string,date:Date){const parts=new Intl.DateTimeFormat("en-CA",{timeZone,year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",second:"2-digit",hourCycle:"h23"}).formatToParts(date);const values=Object.fromEntries(parts.map(p=>[p.type,p.value]));return Date.UTC(+values.year,+values.month-1,+values.day,+values.hour,+values.minute,+values.second)-date.getTime()}
function startFor(period:CeoPeriod,timeZone:string){const now=new Date();const p=new Intl.DateTimeFormat("en-CA",{timeZone,year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(now);const v=Object.fromEntries(p.map(x=>[x.type,x.value]));const guess=new Date(Date.UTC(+v.year,+v.month-1,+v.day));const start=new Date(guess.getTime()-offsetMs(timeZone,guess));if(period!=="today")start.setUTCDate(start.getUTCDate()-(Number(period)-1));return start}
export function normalizeCeoFilters(input:{period?:string;unit?:string}):CeoFilters{return{period:["today","7","30"].includes(input.period??"")?input.period as CeoPeriod:"today",unitId:input.unit??"all"}}

export const getCeoAnalytics=cache(async(filters:CeoFilters)=>{
  const access=await requireArea("ceo");const supabase=await createClient();const authorized=[...new Set(access.assignments.map(a=>String(a.unit_id)))];
  const{data:unitRows}=await supabase.from("parking_units").select("id,name,capacity,timezone,is_active").in("id",authorized).order("name");const units=(unitRows??[]) as CeoUnit[];
  const selected=filters.unitId!=="all"&&authorized.includes(filters.unitId)?units.filter(u=>u.id===filters.unitId):units;const ids=selected.map(u=>u.id);const timezone=selected[0]?.timezone??units[0]?.timezone??"America/Bahia";const since=startFor(filters.period,timezone);const sinceIso=since.toISOString();
  if(!ids.length)return emptyAnalytics(filters,units,sinceIso);
  const periodMs=Date.now()-since.getTime();const previousSince=new Date(since.getTime()-periodMs);
  const[sessionsResult,activeResult,paymentsResult,previousPaymentsResult,shiftsResult,rolesResult,tariffsResult,subscriptionsResult,periodsResult,runsResult]=await Promise.all([
    supabase.from("parking_sessions").select("id,unit_id,vehicle_id,plate_snapshot,vehicle_type,status,entered_at,exited_at,final_amount,calculated_amount,payment_status,entry_mode,financial_obligation,monthly_subscription_id,monthly_billing_period_id,monthly_coverage_reason,theoretical_amount,entry_operator_id,exit_operator_id").in("unit_id",ids).or(`entered_at.gte.${sinceIso},exited_at.gte.${sinceIso}`).order("entered_at",{ascending:false}).limit(1000),
    supabase.from("parking_sessions").select("id,unit_id,vehicle_id,plate_snapshot,vehicle_type,status,entered_at,exited_at,final_amount,calculated_amount,payment_status,entry_mode,financial_obligation,monthly_subscription_id,monthly_billing_period_id,monthly_coverage_reason,theoretical_amount,entry_operator_id,exit_operator_id").in("unit_id",ids).in("status",[...occupying]).order("entered_at",{ascending:false}),
    supabase.from("payments").select("id,unit_id,payment_subject_type,parking_session_id,monthly_billing_period_id,amount,gross_amount,fee_amount,net_amount,method,payment_channel,provider,provider_environment,operational_status,settlement_status,status,manual_confirmation,paid_at,created_at,received_by,cash_shift_id,parking_sessions(plate_snapshot,entered_at),monthly_billing_periods(reference_year,reference_month)").in("unit_id",ids).or(`created_at.gte.${sinceIso},paid_at.gte.${sinceIso}`).order("created_at",{ascending:false}).limit(1000),
    supabase.from("payments").select("amount,status,paid_at,provider,provider_environment").in("unit_id",ids).eq("status","PAID").gte("paid_at",previousSince.toISOString()).lt("paid_at",sinceIso),
    supabase.from("cash_shifts").select("id,unit_id,operator_id,opened_at,closed_at,opening_amount,status,declared_cash_amount,expected_cash_amount,difference_amount,notes").in("unit_id",ids).or(`opened_at.gte.${sinceIso},closed_at.gte.${sinceIso}`).order("opened_at",{ascending:false}).limit(500),
    supabase.from("user_unit_roles").select("user_id,unit_id,role").in("unit_id",ids),
    supabase.from("tariff_rules").select("id,unit_id,name,vehicle_type,version_number,is_active,first_hour_amount,additional_amount,additional_fraction_minutes,grace_minutes,daily_cap_amount,daily_after_minutes").in("unit_id",ids).eq("is_active",true),
    supabase.from("monthly_subscriptions").select("id,unit_id,status,contracted_price,starts_on,cancel_at_period_end").in("unit_id",ids).not("plan_id","is",null),
    supabase.from("monthly_billing_periods").select("id,subscription_id,unit_id,reference_year,reference_month,due_date,grace_until,status").in("unit_id",ids),
    supabase.from("monthly_billing_generation_runs").select("id,unit_id,failed_count,started_at,finished_at").in("unit_id",ids).order("started_at",{ascending:false}).limit(100),
  ]);
  const sessions=(sessionsResult.data??[]) as CeoSession[];const active=(activeResult.data??[]) as CeoSession[];const payments=(paymentsResult.data??[]) as unknown as CeoPayment[];const previousPayments=previousPaymentsResult.data??[];const previousRevenue=previousPayments.reduce((sum,row)=>sum+Number(row.amount),0);const shifts=(shiftsResult.data??[]) as CeoShift[];const roles=rolesResult.data??[];const tariffs=tariffsResult.data??[];const subscriptions=(subscriptionsResult.data??[]) as ContractRow[];const periods=(periodsResult.data??[]) as MonthlyPeriodRow[];const runs=(runsResult.data??[]) as GenerationRunRow[];
  const profileIds=[...new Set([...roles.map(r=>r.user_id),...payments.map(p=>p.received_by).filter(Boolean),...shifts.map(s=>s.operator_id)] as string[])];const{data:profiles}=profileIds.length?await supabase.from("profiles").select("id,full_name,is_active").in("id",profileIds):{data:[]};const names=Object.fromEntries((profiles??[]).map(p=>[p.id,p.full_name]));
  const paid=payments.filter(p=>p.status==="PAID"&&p.paid_at&&new Date(p.paid_at)>=since);const revenue=paid.reduce((s,p)=>s+Number(p.amount),0);const entrances=sessions.filter(s=>new Date(s.entered_at)>=since);const exits=sessions.filter(s=>s.exited_at&&new Date(s.exited_at)>=since);const durations=exits.map(s=>(new Date(s.exited_at!).getTime()-new Date(s.entered_at).getTime())/60000).filter(n=>n>=0);const capacity=selected.reduce((s,u)=>s+u.capacity,0);const method=(m:string)=>{const rows=paid.filter(p=>p.method===m);return{amount:rows.reduce((s,p)=>s+Number(p.amount),0),count:rows.length,percentage:revenue?rows.reduce((s,p)=>s+Number(p.amount),0)/revenue*100:0}};
  const namesByUnit=new Map(selected.map(unit=>[unit.id,unit.name]));const monthlyAlerts=monthlyAlertSeeds(subscriptions,periods,runs).map(alert=>({...alert,unitName:namesByUnit.get(alert.unitId)??"Unidade"}));const alerts=[...buildAlerts(selected,active,shifts),...monthlyAlerts].sort((a,b)=>({Crítico:0,Atenção:1,Info:2}[a.severity]-{Crítico:0,Atenção:1,Info:2}[b.severity]));const unitSummaries=selected.map(unit=>{const ua=active.filter(s=>s.unit_id===unit.id);const ue=entrances.filter(s=>s.unit_id===unit.id);const ux=exits.filter(s=>s.unit_id===unit.id);const up=paid.filter(p=>p.unit_id===unit.id);const ud=ux.map(s=>(new Date(s.exited_at!).getTime()-new Date(s.entered_at).getTime())/60000);return{...unit,active:ua.length,available:Math.max(0,unit.capacity-ua.length),occupancy:unit.capacity?ua.length/unit.capacity*100:0,entries:ue.length,exits:ux.length,revenue:up.reduce((s,p)=>s+Number(p.amount),0),pending:sessions.filter(s=>s.unit_id===unit.id&&s.financial_obligation!=="WAIVED_BY_MONTHLY_COVERAGE"&&s.payment_status==="PENDING").length,averageMinutes:ud.length?ud.reduce((a,b)=>a+b,0)/ud.length:0,alerts:alerts.filter(a=>a.unitId===unit.id).length}});
  const buckets=makeBuckets(filters.period,since,timezone,paid,entrances,exits,capacity);
  const casualRevenue=paid.filter(p=>p.payment_subject_type==="PARKING_SESSION").reduce((s,p)=>s+Number(p.amount),0);const monthlyRevenue=paid.filter(p=>p.payment_subject_type==="MONTHLY_BILLING_PERIOD").reduce((s,p)=>s+Number(p.amount),0);
  return{filters,periodStart:sinceIso,units,selectedUnits:selected,sessions,active,payments,previousPayments,paid,shifts,roles,tariffs,profiles:profiles??[],names,alerts,unitSummaries,buckets,mrr:contractedMrr(subscriptions),coverage:coverageAnalytics(entrances),metrics:{revenue,casualRevenue,monthlyRevenue,previousRevenue,active:active.length,capacity,occupancy:capacity?active.length/capacity*100:0,entries:entrances.length,exits:exits.length,ticket:paid.length?revenue/paid.length:0,averageMinutes:durations.length?durations.reduce((a,b)=>a+b,0)/durations.length:0,payments:paid.length,cashDifference:shifts.reduce((s,x)=>s+Number(x.difference_amount??0),0)},methods:{CASH:method("CASH"),CARD:method("CARD"),PIX:method("PIX"),DEBIT_CARD:method("DEBIT_CARD"),CREDIT_CARD:method("CREDIT_CARD")},updatedAt:new Date().toISOString()};
});
function buildAlerts(units:CeoUnit[],active:CeoSession[],shifts:CeoShift[]):CeoAlert[]{const names=new Map(units.map(u=>[u.id,u.name]));const out:CeoAlert[]=[];for(const s of shifts.filter(x=>Number(x.difference_amount??0)!==0))out.push({id:`shift-${s.id}`,category:"Financeiro",severity:Math.abs(Number(s.difference_amount))>=100?"Crítico":"Atenção",unitId:s.unit_id,unitName:names.get(s.unit_id)??"Unidade",at:s.closed_at??s.opened_at,title:"Diferença de caixa",description:`O caixa apresentou diferença de ${new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(Number(s.difference_amount))}.`,href:`/ceo/financeiro?shift=${s.id}`});const now=Date.now();for(const s of active){const hours=(now-new Date(s.entered_at).getTime())/36e5;if(hours>=12)out.push({id:`long-${s.id}`,category:"Operacional",severity:hours>=24?"Crítico":"Atenção",unitId:s.unit_id,unitName:names.get(s.unit_id)??"Unidade",at:s.entered_at,title:"Sessão longa",description:`${s.plate_snapshot} permanece no pátio há mais de 12 horas.`,href:`/frentista/saidas?session=${s.id}`});if(s.status==="PAYMENT_PENDING"&&hours>=1)out.push({id:`pending-${s.id}`,category:"Financeiro",severity:"Atenção",unitId:s.unit_id,unitName:names.get(s.unit_id)??"Unidade",at:s.entered_at,title:"Pagamento pendente",description:`${s.plate_snapshot} aguarda pagamento há mais de uma hora.`,href:`/frentista/saidas?session=${s.id}`})}for(const u of units){const count=active.filter(s=>s.unit_id===u.id).length;if(u.capacity&&count/u.capacity>=.9)out.push({id:`capacity-${u.id}`,category:"Operacional",severity:count>=u.capacity?"Crítico":"Atenção",unitId:u.id,unitName:u.name,at:new Date().toISOString(),title:"Ocupação elevada",description:`A unidade está com ${Math.round(count/u.capacity*100)}% de ocupação.`,href:`/ceo/unidades/${u.id}`})}return out.sort((a,b)=>({Crítico:0,Atenção:1,Info:2}[a.severity]-{Crítico:0,Atenção:1,Info:2}[b.severity]))}
function makeBuckets(period:CeoPeriod,since:Date,tz:string,paid:CeoPayment[],entries:CeoSession[],exits:CeoSession[],capacity:number){const count=period==="today"?24:Number(period);return Array.from({length:count},(_,i)=>{const start=new Date(since);if(period==="today")start.setUTCHours(start.getUTCHours()+i);else start.setUTCDate(start.getUTCDate()+i);const end=new Date(start);if(period==="today")end.setUTCHours(end.getUTCHours()+1);else end.setUTCDate(end.getUTCDate()+1);const label=period==="today"?new Intl.DateTimeFormat("pt-BR",{timeZone:tz,hour:"2-digit"}).format(start):new Intl.DateTimeFormat("pt-BR",{timeZone:tz,day:"2-digit",month:"2-digit"}).format(start);const inRange=(v:string|null)=>Boolean(v&&new Date(v)>=start&&new Date(v)<end);const ins=entries.filter(s=>inRange(s.entered_at)).length;const outs=exits.filter(s=>inRange(s.exited_at)).length;const bucketPayments=paid.filter(p=>inRange(p.paid_at));return{label,revenue:bucketPayments.reduce((s,p)=>s+Number(p.amount),0),payments:bucketPayments.length,entries:ins,exits:outs,occupancy:capacity?Math.max(0,ins-outs)/capacity*100:0}})}
function emptyAnalytics(filters:CeoFilters,units:CeoUnit[],periodStart:string){const zero={amount:0,count:0,percentage:0};return{filters,periodStart,units,selectedUnits:[],sessions:[],active:[],payments:[],previousPayments:[],paid:[],shifts:[],roles:[],tariffs:[],profiles:[],names:{},alerts:[],unitSummaries:[],buckets:[],mrr:{amount:0,activeAmount:0,suspendedAmount:0,contracts:0,suspendedContracts:0},coverage:{coveredStays:0,monthlyEntries:0,monthlyVehiclesUsed:0,theoreticalWaived:0,averageStaysPerSubscriber:0,monthlyShare:0,casualShare:0,casualEntries:0},metrics:{revenue:0,casualRevenue:0,monthlyRevenue:0,previousRevenue:0,active:0,capacity:0,occupancy:0,entries:0,exits:0,ticket:0,averageMinutes:0,payments:0,cashDifference:0},methods:{CASH:{...zero},CARD:{...zero},PIX:{...zero},DEBIT_CARD:{...zero},CREDIT_CARD:{...zero}},updatedAt:new Date().toISOString()}}
