export const ASAAS_PIX_AUTOMATIC_EVENTS = [
  "PIX_AUTOMATIC_RECURRING_AUTHORIZATION_CREATED",
  "PIX_AUTOMATIC_RECURRING_AUTHORIZATION_ACTIVATED",
  "PIX_AUTOMATIC_RECURRING_AUTHORIZATION_CANCELLED",
  "PIX_AUTOMATIC_RECURRING_AUTHORIZATION_EXPIRED",
  "PIX_AUTOMATIC_RECURRING_AUTHORIZATION_REFUSED",
  "PIX_AUTOMATIC_RECURRING_PAYMENT_INSTRUCTION_CREATED",
  "PIX_AUTOMATIC_RECURRING_PAYMENT_INSTRUCTION_SCHEDULED",
  "PIX_AUTOMATIC_RECURRING_PAYMENT_INSTRUCTION_REFUSED",
  "PIX_AUTOMATIC_RECURRING_PAYMENT_INSTRUCTION_CANCELLED",
] as const;

export type AsaasPixAutomaticEventType = (typeof ASAAS_PIX_AUTOMATIC_EVENTS)[number];

export function isAsaasPixAutomaticEvent(value: unknown): value is AsaasPixAutomaticEventType {
  return typeof value === "string" && (ASAAS_PIX_AUTOMATIC_EVENTS as readonly string[]).includes(value);
}
