import type { ProviderPaymentState } from "./payment-provider";
export type EfiErrorCode="EFI_NOT_CONFIGURED"|"EFI_DISABLED"|"EFI_PRODUCTION_BLOCKED"|"EFI_AUTH_FAILED"|"EFI_CERTIFICATE_MISSING"|"EFI_CERTIFICATE_INVALID"|"EFI_TIMEOUT"|"EFI_PIX_KEY_MISSING"|"EFI_PIX_CREATE_FAILED"|"EFI_PIX_QR_FAILED"|"EFI_RECONCILIATION_FAILED"|"EFI_AMOUNT_MISMATCH"|"EFI_TXID_INVALID"|"EFI_WEBHOOK_INVALID"|"EFI_CREDIT_TOKEN_REQUIRED"|"EFI_CREDIT_CREATE_FAILED"|"EFI_INVALID_RESPONSE"|"EFI_UNKNOWN_STATUS";
export type EfiPixCharge={txid:string;providerPaymentId:string;externalReference:string;amount:number;status:string;expiresAt:string;qrPayload:string|null;qrImageReference:string|null};
export type EfiCreditInput={paymentToken:string;amount:number;externalReference:string};
/** Decodes only in memory; the certificate is never logged or written to disk. */
export function decodeEfiCertificateBase64(value:string|undefined):Buffer{if(!value)throw new Error("EFI_CERTIFICATE_MISSING");const normalized=value.replace(/\s/g,"");if(!/^[A-Za-z0-9+/]+={0,2}$/.test(normalized)||normalized.length%4!==0)throw new Error("EFI_CERTIFICATE_INVALID");const certificate=Buffer.from(normalized,"base64");if(!certificate.length)throw new Error("EFI_CERTIFICATE_INVALID");return certificate}
export function mapEfiStatus(status:string):ProviderPaymentState{switch(status.toUpperCase()){case"ATIVA":case"PENDING":return"PENDING";case"CONCLUIDA":case"PAID":return"PAID";case"EXPIRED":return"EXPIRED";case"REMOVIDA_PELO_USUARIO_RECEBEDOR":case"REMOVIDA_PELO_PSP":case"CANCELLED":return"CANCELLED";default:throw new Error("EFI_UNKNOWN_STATUS")}}
/** Pix txids are 26-35 ASCII alphanumeric characters; validating before requests prevents path injection. */
export function assertEfiTxid(value:unknown):string{if(typeof value!=="string"||!/^[A-Za-z0-9]{26,35}$/.test(value))throw new Error("EFI_TXID_INVALID");return value}
/** Converts Efí's decimal Pix values deterministically, without permissive float comparison. */
export function parseEfiAmountToCents(value:unknown):number{if(typeof value!=="string"&&!Number.isFinite(value))throw new Error("EFI_INVALID_RESPONSE");const match=/^(0|[1-9]\d*)(?:\.(\d{1,2}))?$/.exec(String(value));if(!match)throw new Error("EFI_INVALID_RESPONSE");const whole=Number(match[1]);const fraction=Number((match[2]??"").padEnd(2,"0"));if(!Number.isSafeInteger(whole)||whole>Math.floor((Number.MAX_SAFE_INTEGER-fraction)/100))throw new Error("EFI_INVALID_RESPONSE");return whole*100+fraction}
export function amountToCents(value:number):number{if(!Number.isFinite(value)||value<0)throw new Error("EFI_AMOUNT_MISMATCH");try{return parseEfiAmountToCents(String(value))}catch{throw new Error("EFI_AMOUNT_MISMATCH")}}
export function assertCreditToken(input:Record<string,unknown>):EfiCreditInput{if(typeof input.paymentToken!=="string"||!input.paymentToken)return fail("EFI_CREDIT_TOKEN_REQUIRED");if("pan" in input||"cardNumber" in input||"cvv" in input)return fail("EFI_CREDIT_TOKEN_REQUIRED");if(typeof input.amount!=="number"||typeof input.externalReference!=="string")return fail("EFI_CREDIT_CREATE_FAILED");return{paymentToken:input.paymentToken,amount:input.amount,externalReference:input.externalReference}}
function fail(code:EfiErrorCode):never{throw new Error(code)}
