import Link from "next/link";
import { DashboardShell } from "@/components/dashboard-shell";
import { OperationBadge } from "@/components/operation-badge";
import { getOperatorContext } from "@/lib/operator-data";
import { formatDateTime,formatMoney,formatPaymentMethod,paymentStatus } from "@/lib/operator-format";
import { operatorNav } from "@/lib/operator-nav";
import { createClient } from "@/lib/supabase/server";
export const dynamic="force-dynamic";
type PaymentRow={id:string;amount:number;method:string;status:string;manual_confirmation:boolean;received_by:string|null;paid_at:string|null;created_at:string;parking_session_id:string;parking_sessions:{plate_snapshot:string}|null};
export default async function PaymentsPage(){const{unitId}=await getOperatorContext();const supabase=await createClient();const[{data:unit},{data}]=await Promise.all([supabase.from("parking_units").select("timezone").eq("id",unitId).single(),supabase.from("payments").select("id,amount,method,status,manual_confirmation,received_by,paid_at,created_at,parking_session_id,parking_sessions(plate_snapshot)").eq("unit_id",unitId).order("created_at",{ascending:false}).limit(100)]);const rows=(data??[]) as unknown as PaymentRow[];const operatorIds=[...new Set(rows.map(row=>row.received_by).filter(Boolean) as string[])];const{data:profiles}=operatorIds.length?await supabase.from("profiles").select("id,full_name").in("id",operatorIds):{data:[]};const names=new Map((profiles??[]).map(profile=>[profile.id,profile.full_name]));return <DashboardShell nav={operatorNav} active="Pagamentos" role="Frentista"><div className="mx-auto max-w-6xl space-y-5"><div><h1 className="text-3xl font-bold">Pagamentos do turno</h1><p className="text-sm text-slate-500">Cartão e dinheiro são confirmações operacionais manuais. PIX depende de confirmação futura do provedor.</p></div><section className="overflow-hidden rounded-2xl border bg-white"><div className="hidden md:block"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr><th className="p-4">Placa</th><th>Valor</th><th>Método</th><th>Status</th><th>Operador</th><th>Horário</th><th className="pr-4 text-right">Ação</th></tr></thead><tbody>{rows.map(row=><PaymentTableRow key={row.id} row={row} timezone={unit?.timezone} operator={row.received_by?names.get(row.received_by):undefined}/>)}</tbody></table></div><div className="divide-y md:hidden">{rows.map(row=><PaymentCard key={row.id} row={row} timezone={unit?.timezone} operator={row.received_by?names.get(row.received_by):undefined}/>)}</div>{rows.length===0?<p className="p-8 text-center text-sm text-slate-500">Nenhum pagamento registrado.</p>:null}</section></div></DashboardShell>}
function PaymentTableRow({row,timezone,operator}:{row:PaymentRow;timezone?:string;operator?:string}){const status=paymentStatus(row.status);return <tr className="border-t"><td className="p-4 font-bold">{row.parking_sessions?.plate_snapshot??"—"}</td><td>{formatMoney(row.amount)}</td><td>{formatPaymentMethod(row.method,row.manual_confirmation)}</td><td><OperationBadge {...status}/></td><td>{operator??"Operador não identificado"}</td><td>{formatDateTime(row.paid_at??row.created_at,timezone)}</td><td className="pr-4 text-right"><Link className="font-semibold text-blue-600 hover:underline" href={`/frentista/historico?session=${row.parking_session_id}&status=all&period=30`}>Ver sessão</Link></td></tr>}
function PaymentCard({row,timezone,operator}:{row:PaymentRow;timezone?:string;operator?:string}){const status=paymentStatus(row.status);return <article className="space-y-3 p-4"><div className="flex items-start justify-between"><div><p className="font-bold">{row.parking_sessions?.plate_snapshot??"—"}</p><p className="text-xs text-slate-500">{formatDateTime(row.paid_at??row.created_at,timezone)}</p></div><OperationBadge {...status}/></div><div className="flex justify-between text-sm"><span>{formatPaymentMethod(row.method,row.manual_confirmation)}</span><b>{formatMoney(row.amount)}</b></div><p className="text-xs text-slate-500">Responsável: {operator??"Operador não identificado"}</p><Link className="inline-flex font-semibold text-blue-600" href={`/frentista/historico?session=${row.parking_session_id}&status=all&period=30`}>Ver sessão</Link></article>}

