import { DashboardShell } from "@/components/dashboard-shell";
import { MonthlyPaymentActions } from "@/components/monthly-payment-actions";
import { getOperatorContext } from "@/lib/operator-data";
import { formatMoney } from "@/lib/operator-format";
import { operatorNav } from "@/lib/operator-nav";
import { canUsePayment, getPaymentAvailability } from "@/lib/payments/payment-availability";
import { createAdminClient } from "@/lib/supabase/admin";
import { createClient } from "@/lib/supabase/server";
export const dynamic="force-dynamic";

type Period={id:string;reference_year:number;reference_month:number;due_date:string;amount:number;status:string;monthly_subscriptions:{customer_id:string;plan_name:string}|null;payments:{id:string;method:string;status:string;paid_at:string|null}[]};
export default async function MonthlyPage(){
 const{unitId}=await getOperatorContext();const supabase=await createClient();const availability=await getPaymentAvailability(unitId);
 const{data}=await supabase.from("monthly_billing_periods").select("id,reference_year,reference_month,due_date,amount,status,monthly_subscriptions(customer_id,plan_name),payments(id,method,status,paid_at)").eq("unit_id",unitId).order("due_date",{ascending:false}).limit(100);
 const periods=(data??[]) as unknown as Period[];const customerIds=[...new Set(periods.map(p=>p.monthly_subscriptions?.customer_id).filter(Boolean) as string[])];const admin=createAdminClient();const{data:customers}=customerIds.length?await admin.from("customer_profiles").select("user_id,full_name").in("user_id",customerIds):{data:[]};const names=new Map((customers??[]).map(c=>[c.user_id,c.full_name]));
 return <DashboardShell nav={operatorNav} active="Mensalistas" role="Frentista"><div className="mx-auto max-w-5xl space-y-5"><div><h1 className="text-3xl font-bold">Mensalistas</h1><p className="text-sm text-slate-500">Consulte competências e regularize mensalidades da sua unidade. Planos e contratos permanecem administrativos.</p></div><div className="space-y-3">{periods.map(period=>{const payment=period.payments.find(p=>p.status==="PAID")??period.payments.find(p=>p.status==="PENDING");const payable=period.status==="PENDING";return <article key={period.id} className="rounded-2xl border bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-bold">{names.get(period.monthly_subscriptions?.customer_id??"")??"Cliente mensalista"}</h2><p className="text-sm text-slate-500">{period.monthly_subscriptions?.plan_name} · competência {String(period.reference_month).padStart(2,"0")}/{period.reference_year}</p><p className="mt-2 text-sm">Vencimento: {new Date(`${period.due_date}T12:00:00`).toLocaleDateString("pt-BR")}</p></div><div className="text-right"><b className="text-xl">{formatMoney(period.amount)}</b><p className="text-xs font-semibold text-slate-500">{period.status==="PAID"?"Pago":payment?"Processando":"Aguardando"}</p></div></div>{payable&&!payment?<MonthlyPaymentActions billingPeriodId={period.id} allowCash pixEnabled={canUsePayment(availability,"PIX","QR","ASAAS")} creditEnabled={canUsePayment(availability,"CREDIT_CARD","HOSTED_CHECKOUT","ASAAS")}/>:null}{payment?<p className="mt-3 rounded-xl bg-slate-50 p-3 text-sm">Pagamento: {payment.method} · {payment.status}</p>:null}</article>})}{!periods.length?<p className="rounded-2xl border bg-white p-8 text-center text-sm text-slate-500">Nenhuma competência encontrada.</p>:null}</div></div></DashboardShell>
}
