import Link from "next/link";
import { AlertTriangle } from "lucide-react";
import { DashboardShell } from "@/components/dashboard-shell";
import { CeoPageHeader } from "@/components/ceo-page-header";
import { CeoFilters } from "@/components/ceo-filters";
import { ceoNav } from "@/lib/ceo-nav";
import { getCeoAnalytics, normalizeCeoFilters } from "@/lib/ceo-analytics";
import { formatDateTime, formatMoney, formatPaymentMethod, formatPaymentStatus } from "@/lib/operator-format";
export const dynamic = "force-dynamic";

export default async function Page({ searchParams }: { searchParams: Promise<{ period?: string; unit?: string; method?: string; status?: string; shift?: string }> }) {
  const query = await searchParams; const data = await getCeoAnalytics(normalizeCeoFilters(query));
  const unitNames = new Map(data.units.map((unit) => [unit.id, unit.name]));
  const payments = data.payments.filter((payment) => (!query.method || query.method === "all" || payment.method === query.method) && (!query.status || query.status === "all" || payment.status === query.status));
  const selectedShift = data.shifts.find((shift) => shift.id === query.shift);
  const cashReceived = (shiftId: string) => data.paid.filter((payment) => payment.cash_shift_id === shiftId && payment.method === "CASH").reduce((sum, payment) => sum + Number(payment.amount), 0);
  const expectedCash = (shift: (typeof data.shifts)[number]) => shift.status === "OPEN" ? Number(shift.opening_amount) + cashReceived(shift.id) : shift.expected_cash_amount;
  for (const shift of data.shifts) if (shift.status === "OPEN") shift.expected_cash_amount = expectedCash(shift);
  return <DashboardShell nav={ceoNav} active="Financeiro" role="CEO"><div className="mx-auto max-w-[1500px] space-y-5">
    <CeoPageHeader title="Financeiro" description="Analise receitas confirmadas, pagamentos e caixas."><CeoFilters units={data.units}/></CeoPageHeader>
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Receita confirmada",formatMoney(data.metrics.revenue)],["Estacionamento avulso",formatMoney(data.metrics.casualRevenue)],["Mensalidades recebidas",formatMoney(data.metrics.monthlyRevenue)],["Dinheiro",formatMoney(data.methods.CASH.amount)],["Cartão legado",formatMoney(data.methods.CARD.amount)],["Crédito online",formatMoney(data.methods.CREDIT_CARD.amount)],["PIX",formatMoney(data.methods.PIX.amount)],["Pagamentos",String(data.metrics.payments)]].map(([label,value])=><Kpi key={label} label={label} value={value}/>) }<Kpi label="Diferença de caixa" value={formatMoney(data.metrics.cashDifference)} warning={data.metrics.cashDifference !== 0}/></div>
    <section className="overflow-hidden rounded-2xl border bg-white"><div className="flex flex-wrap items-center justify-between gap-3 p-5"><h2 className="font-bold">Pagamentos</h2><form className="flex flex-wrap gap-2"><input type="hidden" name="period" value={data.filters.period}/><input type="hidden" name="unit" value={data.filters.unitId}/><select name="method" defaultValue={query.method??"all"} className="h-9 rounded-lg border px-2 text-sm"><option value="all">Todos os métodos</option><option value="CASH">Dinheiro</option><option value="PIX">PIX</option><option value="CARD">Cartão legado</option><option value="DEBIT_CARD">Débito</option><option value="CREDIT_CARD">Crédito</option></select><select name="status" defaultValue={query.status??"all"} className="h-9 rounded-lg border px-2 text-sm"><option value="all">Todos os status</option><option value="PAID">Pago</option><option value="PENDING">Pendente</option><option value="FAILED">Falhou</option></select><button className="rounded-lg bg-blue-600 px-3 text-sm font-bold text-white">Filtrar</button></form></div>
      {payments.length ? <div className="overflow-x-auto"><table className="w-full min-w-[980px] text-left text-xs"><thead className="bg-slate-50 text-slate-500"><tr>{["Horário","Placa","Entrada","Método","Valor","Status","Operador","Unidade","Ação"].map((label)=><th key={label} className="px-4 py-3">{label}</th>)}</tr></thead><tbody>{payments.map((payment)=><tr key={payment.id} className="border-t"><td className="px-4 py-3">{formatDateTime(payment.paid_at??payment.created_at)}</td><td className="font-bold">{payment.parking_sessions?.plate_snapshot??"—"}</td><td>{payment.parking_sessions?.entered_at?formatDateTime(payment.parking_sessions.entered_at):"—"}</td><td>{formatPaymentMethod(payment.method,payment.manual_confirmation)}</td><td className="font-bold">{formatMoney(payment.amount)}</td><td>{formatPaymentStatus(payment.status)}</td><td><Operator name={payment.received_by?data.names[payment.received_by]??"Operador não identificado":"—"}/></td><td>{unitNames.get(payment.unit_id)}</td><td>{payment.parking_sessions?<Link className="font-semibold text-blue-600" href={`/ceo/relatorios?period=${data.filters.period}&unit=${data.filters.unitId}&session=${payment.parking_session_id}`}>Ver sessão</Link>:"—"}</td></tr>)}</tbody></table></div> : <Empty text="Nenhum pagamento encontrado neste período."/>}
    </section>
    <section className="rounded-2xl border bg-white"><h2 className="p-5 font-bold">Caixas</h2>{data.shifts.length?<div className="grid gap-3 p-4 lg:grid-cols-2">{data.shifts.map((shift)=><article key={shift.id} className={`rounded-xl border p-4 ${Number(shift.difference_amount)!==0?"border-amber-200 bg-amber-50/30":""}`}><div className="flex items-center justify-between"><Operator name={data.names[shift.operator_id]??"Operador não identificado"}/><span className={`rounded-full px-2 py-1 text-xs font-bold ${shift.status==="OPEN"?"bg-emerald-50 text-emerald-700":"bg-slate-100 text-slate-600"}`}>{shift.status==="OPEN"?"Aberto":"Fechado"}</span></div><p className="mt-1 text-xs text-slate-500">{unitNames.get(shift.unit_id)} · abertura {formatDateTime(shift.opened_at)}</p><div className="mt-4 grid grid-cols-2 gap-3 text-sm"><Cell label="Saldo inicial" value={formatMoney(shift.opening_amount)}/><Cell label="Dinheiro recebido" value={formatMoney(cashReceived(shift.id))}/><Cell label="Esperado" value={formatMoney(shift.expected_cash_amount)}/><Cell label="Declarado" value={shift.declared_cash_amount==null?"—":formatMoney(shift.declared_cash_amount)}/></div><div className="mt-4 flex items-center justify-between"><b className={Number(shift.difference_amount)!==0?"text-amber-700":""}>Diferença: {formatMoney(shift.difference_amount)}</b><Link className="text-sm font-semibold text-blue-600" href={`?period=${data.filters.period}&unit=${data.filters.unitId}&shift=${shift.id}`}>Ver detalhe</Link></div></article>)}</div>:<Empty text="Nenhum caixa encontrado neste período."/>}</section>
    {selectedShift?<section className="rounded-2xl border border-blue-100 bg-white p-5"><div className="flex justify-between"><h2 className="font-bold">Detalhe do caixa</h2><Link href={`?period=${data.filters.period}&unit=${data.filters.unitId}`} className="text-sm text-blue-600">Fechar</Link></div><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Cell label="Operador" value={data.names[selectedShift.operator_id]??"Operador não identificado"}/><Cell label="Unidade" value={unitNames.get(selectedShift.unit_id)??"—"}/><Cell label="Abertura" value={formatDateTime(selectedShift.opened_at)}/><Cell label="Fechamento" value={selectedShift.closed_at?formatDateTime(selectedShift.closed_at):"Em aberto"}/><Cell label="Saldo inicial" value={formatMoney(selectedShift.opening_amount)}/><Cell label="Pagamentos em dinheiro" value={formatMoney(cashReceived(selectedShift.id))}/><Cell label="Esperado" value={formatMoney(selectedShift.expected_cash_amount)}/><Cell label="Declarado" value={selectedShift.declared_cash_amount==null?"—":formatMoney(selectedShift.declared_cash_amount)}/><Cell label="Diferença" value={formatMoney(selectedShift.difference_amount)}/></div>{selectedShift.notes?<p className="mt-4 rounded-xl bg-slate-50 p-3 text-sm"><b>Observação:</b> {selectedShift.notes}</p>:null}</section>:null}
  </div></DashboardShell>;
}
function Kpi({label,value,warning=false}:{label:string;value:string;warning?:boolean}){return <div className={`rounded-2xl border bg-white p-4 ${warning?"border-amber-300 bg-amber-50/40":""}`}><p className="flex items-center gap-1 text-xs text-slate-500">{warning?<AlertTriangle className="size-4 text-amber-600"/>:null}{label}</p><p className={`mt-1 text-xl font-bold ${warning?"text-amber-700":""}`}>{value}</p></div>}
function Cell({label,value}:{label:string;value:string}){return <div><p className="text-xs text-slate-500">{label}</p><p className="font-semibold">{value}</p></div>}
function Operator({name}:{name:string}){return <span className="inline-flex items-center gap-2"><i className="grid size-7 place-items-center rounded-full bg-blue-50 text-xs font-bold text-blue-700">{name.charAt(0).toUpperCase()}</i><span>{name}</span></span>}
function Empty({text}:{text:string}){return <p className="border-t p-8 text-center text-sm text-slate-500">{text}</p>}

