import { BarChart3, CarFront, CheckCircle2, LockKeyhole, ParkingSquare, ShieldCheck, Smartphone, UserRound } from "lucide-react";
import { redirect } from "next/navigation";
import { getAccess } from "@/lib/auth";
import { LoginForm } from "./login-form";

export const dynamic = "force-dynamic";
export default async function LoginPage() {
  const access = await getAccess();
  if (access) redirect(`/${access.area}`);
  return <main className="min-h-screen bg-[#f4f7fc] text-slate-950 lg:grid lg:grid-cols-[1.05fr_.95fr]">
    <section className="relative hidden overflow-hidden bg-gradient-to-br from-blue-700 via-blue-600 to-indigo-800 p-12 text-white lg:flex lg:flex-col lg:justify-between"><div className="absolute -right-24 -top-24 size-96 rounded-full bg-white/10 blur-3xl" /><div className="relative flex items-center gap-3"><span className="grid size-12 place-items-center rounded-2xl bg-white text-blue-700"><ParkingSquare className="size-6" /></span><div><p className="text-2xl font-bold">Star Cavalos</p><p className="text-sm text-blue-100">Gestão inteligente de estacionamento</p></div></div><div className="relative max-w-xl"><span className="inline-flex rounded-full border border-white/20 bg-white/10 px-3 py-1.5 text-xs font-semibold">Operação, gestão e atendimento em um só lugar</span><h1 className="mt-6 text-5xl font-bold leading-[1.1]">Controle completo, acesso certo para cada pessoa.</h1><p className="mt-5 text-lg leading-8 text-blue-100">Cada conta visualiza somente as informações e ferramentas autorizadas para seu perfil.</p><div className="mt-10 grid grid-cols-3 gap-3"><Feature icon={CarFront} label="Frentista" text="Operação diária" /><Feature icon={BarChart3} label="CEO" text="Visão estratégica" /><Feature icon={UserRound} label="Cliente" text="Estadia e PIX" /></div></div><p className="relative text-xs text-blue-200">© 2026 Star Cavalos. Ambiente protegido.</p></section>
    <section className="flex min-h-screen items-center justify-center px-4 py-10 sm:px-8"><div className="w-full max-w-[500px]"><div className="mb-8 flex items-center gap-3 lg:hidden"><span className="grid size-11 place-items-center rounded-xl bg-blue-600 text-white"><ParkingSquare className="size-6" /></span><div><p className="text-xl font-bold">Star Cavalos</p><p className="text-xs text-slate-500">Gestão de estacionamento</p></div></div><div className="rounded-[28px] border bg-white p-6 shadow-2xl shadow-slate-200/70 sm:p-9"><span className="grid size-12 place-items-center rounded-2xl bg-blue-50 text-blue-600"><LockKeyhole className="size-6" /></span><h2 className="mt-5 text-3xl font-bold">Acesse sua conta</h2><p className="mt-2 text-sm leading-6 text-slate-500">Use as credenciais cadastradas pelo administrador. Seu painel será identificado automaticamente.</p><div className="my-7"><LoginForm /></div><div className="space-y-3 border-t pt-6"><SecurityLine icon={ShieldCheck} text="Autorização verificada no servidor e no banco" /><SecurityLine icon={CheckCircle2} text="Cada perfil acessa somente sua própria área" /><SecurityLine icon={Smartphone} text="Compatível com computador, tablet e celular" /></div></div><p className="mt-5 text-center text-xs leading-5 text-slate-400">Não possui acesso ou esqueceu a senha? Solicite ajuda ao administrador.</p></div></section>
  </main>;
}
function Feature({ icon: Icon, label, text }: { icon: typeof CarFront; label: string; text: string }) { return <div className="rounded-2xl border border-white/15 bg-white/10 p-4"><Icon className="size-5" /><p className="mt-3 font-bold">{label}</p><p className="mt-1 text-xs text-blue-100">{text}</p></div>; }
function SecurityLine({ icon: Icon, text }: { icon: typeof ShieldCheck; text: string }) { return <p className="flex items-center gap-3 text-xs text-slate-500"><Icon className="size-4 shrink-0 text-emerald-600" />{text}</p>; }
