import { Bell,Building2,CalendarDays,CarFront,CircleDollarSign,CircleGauge,CircleHelp,FileText,Handshake,Home,Settings,ShieldAlert,Users,WalletCards } from "lucide-react";
import { DashboardShell,DemoNotice,type NavItem } from "@/components/dashboard-shell";
import { MetricCard,Sparkline,StatusPill } from "@/components/dashboard-parts";
const nav:NavItem[]=[{label:"Painel do CEO",href:"/ceo",icon:Home},{label:"Unidades",href:"/ceo/unidades",icon:Building2},{label:"Financeiro",href:"/ceo/financeiro",icon:WalletCards},{label:"Relatórios",href:"/ceo/relatorios",icon:FileText},{label:"Convênios",href:"/ceo/convenios",icon:Handshake},{label:"Clientes",href:"/ceo/clientes",icon:Users},{label:"Equipe",href:"/ceo/equipe",icon:Users},{label:"Alertas",href:"/ceo/alertas",icon:Bell},{label:"Configurações",href:"/ceo/configuracoes",icon:Settings},{label:"Ajuda",href:"/ceo/ajuda",icon:CircleHelp}];
export default function CeoPage(){return <DashboardShell nav={nav} active="Painel do CEO" role="CEO" aside={<div className="rounded-2xl border bg-white p-4 text-xs"><p className="font-bold">Vis&atilde;o consolidada</p><div className="my-3 h-px bg-slate-200"/><p className="flex gap-2"><CalendarDays className="size-4"/>Hoje</p><p className="mt-4 text-slate-500">Todas as unidades<br/>3 unidades</p></div>}><div className="mx-auto max-w-[1500px] space-y-4"><div className="flex items-end justify-between"><div><h1 className="text-3xl font-bold">Painel do CEO</h1><p className="text-sm text-slate-500">Vis&atilde;o estrat&eacute;gica do desempenho do estacionamento.</p></div><DemoNotice/></div>
<div id="financeiro" className="scroll-mt-24 grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><MetricCard label="Receita hoje" value="R$ 12.456" icon={CircleDollarSign} tone="green" note="18,6% vs ontem"/><MetricCard label="Veículos no pátio" value="186" icon={CarFront} note="8,2%"/><MetricCard label="Ocupação" value="72%" icon={CircleGauge} tone="violet" note="6 p.p."/><MetricCard label="Ticket médio" value="R$ 28,40" icon={WalletCards} tone="orange" note="7,4%"/><MetricCard label="Mensalistas ativos" value="412" icon={Users} tone="green" note="2,0%"/><MetricCard label="Pagamentos PIX" value="R$ 6.752" icon={CircleDollarSign} tone="green"/></div>
<div id="relatorios" className="scroll-mt-24 grid gap-4 xl:grid-cols-2"><Chart title="Receita ao longo do tempo"><Sparkline/></Chart><Chart title="Ocupa&ccedil;&atilde;o ao longo do dia"><Sparkline color="#12a66a" fill="#dff8ec" variant={2}/></Chart></div>
<div className="grid gap-4 xl:grid-cols-[.85fr_1.15fr_1.1fr]"><section className="rounded-2xl border bg-white p-4"><h2 className="font-bold">Formas de pagamento</h2><div className="mt-4 flex items-center gap-5"><div className="donut grid size-32 place-items-center rounded-full"><span className="grid size-20 place-items-center rounded-full bg-white text-center text-xs font-bold">Total<br/>R$ 12.456</span></div><div className="space-y-3 text-xs"><Legend color="bg-emerald-500" label="PIX" value="54%"/><Legend color="bg-blue-600" label="Cartão" value="33%"/><Legend color="bg-orange-500" label="Dinheiro" value="13%"/></div></div></section>
<section id="alertas" className="scroll-mt-24 rounded-2xl border bg-white p-4"><div className="flex justify-between"><h2 className="font-bold">Alertas operacionais</h2><span className="text-xs text-blue-600">Ver todos</span></div><div className="mt-3 space-y-2"><Alert icon={WalletCards} title="Diferen&ccedil;a de caixa" text="Unidade Centro: diferen&ccedil;a de R$ 125,00." tone="amber"/><Alert icon={ShieldAlert} title="Mensalidades vencidas" text="23 mensalidades em aberto." tone="red"/><Alert icon={CircleGauge} title="Pico previsto" text="Quinta-feira, das 17h &agrave;s 20h." tone="blue"/></div></section>
<section id="insights" className="scroll-mt-24 rounded-2xl border bg-white p-4"><h2 className="font-bold">Insights do neg&oacute;cio</h2><div className="mt-3 grid gap-2"><Insight label="Melhor horário hoje" value="18:00 - 19:00"/><Insight label="Receita do mês" value="R$ 236.780,00"/><Insight label="Top convênio" value="Empresa Alpha"/></div></section></div>
<section id="unidades" className="scroll-mt-24 overflow-x-auto rounded-2xl border bg-white"><h2 className="px-5 py-4 font-bold">Resumo operacional por unidade</h2><table className="w-full min-w-[850px] text-left text-xs"><thead className="bg-slate-50 text-slate-500"><tr>{["Unidade","Entradas hoje","Saídas hoje","Veículos no pátio","Ocupação","Permanência média","Pendências","Receita hoje"].map(h=><th key={h} className="px-4 py-3">{h}</th>)}</tr></thead><tbody>{[["Unidade Centro","342","298","128","78%","2h 36m","R$ 1.245","R$ 8.452"],["Unidade Aeroporto","276","241","58","66%","3h 12m","R$ 820","R$ 5.132"],["Unidade Shopping","198","176","44","74%","2h 08m","R$ 610","R$ 2.872"]].map(r=><tr key={r[0]} className="border-t">{r.map((c,i)=><td key={i} className="px-4 py-3 font-medium">{i===4?<StatusPill>{c}</StatusPill>:c}</td>)}</tr>)}</tbody></table></section></div></DashboardShell>}
function Chart({title,children}:{title:string;children:React.ReactNode}){return <section className="rounded-2xl border bg-white p-4"><h2 className="font-bold">{title}</h2><div className="mt-4 h-52">{children}</div><div className="grid grid-cols-2 border-t pt-3 text-xs"><div><p className="text-slate-500">Resultado acumulado</p><b className="text-lg">R$ 12.456,00</b></div><div><p className="text-slate-500">M&aacute;xima de hoje</p><b className="text-lg">93% &agrave;s 18:30</b></div></div></section>}
function Legend({color,label,value}:{color:string;label:string;value:string}){return <div className="flex items-center gap-2"><i className={"size-2.5 rounded-full "+color}/><span className="w-16">{label}</span><b>{value}</b></div>}
function Alert({icon:Icon,title,text,tone}:{icon:typeof Bell;title:string;text:string;tone:"amber"|"red"|"blue"}){return <div className="flex items-center gap-3 rounded-xl border p-3"><Icon className="size-4"/><div className="flex-1"><p className="text-xs font-bold">{title}</p><p className="text-[10px] text-slate-500">{text}</p></div><StatusPill tone={tone}>{tone==="red"?"Crítico":tone==="amber"?"Atenção":"Info"}</StatusPill></div>}
function Insight({label,value}:{label:string;value:string}){return <div className="rounded-xl border p-3"><p className="text-[11px] text-slate-500">{label}</p><p className="mt-1 font-bold">{value}</p></div>}







