import Link from "next/link";
import { ShieldAlert } from "lucide-react";
import { DashboardShell } from "@/components/dashboard-shell";
import { CompleteExitForm,PaymentForm,StartExitForm } from "@/components/session-operation-form";
import { formatDateTime,formatDuration,formatMoney,getOperatorDashboard } from "@/lib/operator-data";
import { operatorNav } from "@/lib/operator-nav";
export const dynamic="force-dynamic";
export default async function ExitsPage({searchParams}:{searchParams:Promise<{session?:string}>}) {
  const [{session},data]=await Promise.all([searchParams,getOperatorDashboard()]); const selected=data.active_sessions.find(s=>s.id===session)??data.active_sessions[0];
  return <DashboardShell nav={operatorNav} active="SaÃ­das" role="Frentista"><div className="mx-auto max-w-6xl space-y-5">
    <div><h1 className="text-3xl font-bold">SaÃ­da de veÃ­culo</h1><p className="text-sm text-slate-500">Selecione uma placa ativa e siga o fluxo de cobranÃ§a.</p></div>
    <div className="grid gap-4 lg:grid-cols-[.85fr_1.15fr]"><section className="rounded-2xl border bg-white p-4"><h2 className="font-bold">VeÃ­culos ativos</h2><div className="mt-3 space-y-2">{data.active_sessions.map(s=><Link key={s.id} href={`/frentista/saidas?session=${s.id}`} className={`flex justify-between rounded-xl border p-3 ${selected?.id===s.id?"border-blue-500 bg-blue-50":""}`}><b>{s.plate}</b><span className="text-sm text-slate-500">{formatDuration(s.duration_minutes)}</span></Link>)}{data.active_sessions.length===0&&<p className="py-8 text-center text-sm text-slate-500">Nenhum veÃ­culo no pÃ¡tio.</p>}</div></section>
      {selected?<section className="rounded-2xl border bg-white p-6 shadow-sm"><div className="flex justify-between"><div><p className="text-sm text-slate-500">Placa</p><h2 className="text-3xl font-bold">{selected.plate}</h2></div><span className="h-fit rounded-full bg-blue-50 px-3 py-1 text-xs font-bold text-blue-700">{selected.status}</span></div><dl className="my-6 grid grid-cols-2 gap-4 border-y py-5 text-sm"><div><dt className="text-slate-500">Entrada</dt><dd className="font-semibold">{formatDateTime(selected.entered_at,data.unit.timezone)}</dd></div><div><dt className="text-slate-500">PermanÃªncia</dt><dd className="font-semibold">{formatDuration(selected.duration_minutes)}</dd></div><div><dt className="text-slate-500">Tarifa</dt><dd className="font-semibold">{selected.tariff_name}</dd></div><div><dt className="text-slate-500">Valor</dt><dd className="text-xl font-bold text-emerald-600">{formatMoney(selected.amount)}</dd></div></dl>
        {selected.status==="OPEN"&&<StartExitForm sessionId={selected.id}/>} {selected.status==="PAYMENT_PENDING"&&<div className="space-y-3"><p className="text-sm font-semibold">Registrar recebimento manual</p><div className="grid grid-cols-2 gap-3"><PaymentForm sessionId={selected.id} method="CARD"/><PaymentForm sessionId={selected.id} method="CASH"/></div><p className="flex gap-2 rounded-xl bg-amber-50 p-3 text-xs text-amber-800"><ShieldAlert className="size-4 shrink-0"/>PIX integrado ainda nÃ£o configurado; nÃ£o Ã© possÃ­vel confirmar PIX manualmente.</p></div>}{selected.status==="PAID"&&<CompleteExitForm sessionId={selected.id}/>}</section>:<section className="grid min-h-64 place-items-center rounded-2xl border bg-white text-slate-500">Selecione um veÃ­culo.</section>}
    </div></div></DashboardShell>;
}
