"use client";
import Image from "next/image";
import QRCode from "qrcode";
import { CreditCard, ExternalLink, LoaderCircle, QrCode, RefreshCw } from "lucide-react";
import { useRouter } from "next/navigation";
import { useCallback,useEffect,useRef,useState } from "react";
type Checkout={state:string;amount:number;hostedPaymentUrl:string|null;expiresAt:string|null};
export function CreditCheckoutPanel({sessionId,billingPeriodId,resumeExisting=false,onSwitchStart,onSwitchReady}:{sessionId?:string;billingPeriodId?:string;resumeExisting?:boolean;onSwitchStart?:()=>void;onSwitchReady?:()=>void}){const router=useRouter();const[checkout,setCheckout]=useState<Checkout|null>(null);const[loading,setLoading]=useState(false);const[error,setError]=useState<string|null>(null);const[qr,setQr]=useState<string|null>(null);const[expired,setExpired]=useState(false);const resumeRequested=useRef(false);
 const read=useCallback(async(response:Response)=>{const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error==="PAYMENTS_SANDBOX_UNAVAILABLE"?"Checkout temporariamente indisponível.":typeof body.error==="string"?body.error:"Não foi possível abrir o pagamento com cartão.");const value=body.checkout as Checkout|null|undefined;if(!value){setCheckout(null);setExpired(true);setError("O link anterior expirou ou foi encerrado. Gere um novo link de pagamento.");if(!billingPeriodId)router.refresh();return null}if(["CREATE_FAILED","EXPIRED","CANCELLED"].includes(value.state)){setCheckout(null);setExpired(true);setError("O link anterior expirou ou foi cancelado. Gere um novo link de pagamento.");if(!billingPeriodId)router.refresh();return null}if(typeof value.amount!=="number")throw new Error("Resposta de checkout inválida.");setCheckout(value);setExpired(false);setError(null);if(value.state==="PAID")router.refresh();return value},[billingPeriodId,router]);
 const create=async()=>{setLoading(true);setError(null);if(billingPeriodId)onSwitchStart?.();try{const monthly=Boolean(billingPeriodId);const value=await read(await fetch(monthly?"/api/payments/monthly/credit-checkout":"/api/payments/credit-checkout",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(monthly?{billingPeriodId}:{sessionId})}));if(monthly&&value)onSwitchReady?.()}catch(cause){setError(cause instanceof Error?cause.message:"Falha no checkout.")}finally{setLoading(false)}};
 const refresh=useCallback(async()=>{setLoading(true);try{const endpoint=billingPeriodId?`/api/payments/monthly/credit-checkout?billingPeriodId=${encodeURIComponent(billingPeriodId)}`:`/api/payments/credit-checkout?sessionId=${encodeURIComponent(sessionId??"")}`;const value=await read(await fetch(endpoint,{cache:"no-store"}));if(billingPeriodId&&value)onSwitchReady?.()}catch(cause){setError(cause instanceof Error?cause.message:"Falha ao atualizar.")}finally{setLoading(false)}},[billingPeriodId,onSwitchReady,read,sessionId]);
 useEffect(()=>{if(!resumeExisting||checkout||resumeRequested.current)return;resumeRequested.current=true;const timer=window.setTimeout(()=>void refresh(),0);return()=>window.clearTimeout(timer)},[checkout,refresh,resumeExisting]);
 useEffect(()=>{if(!checkout||checkout.state==="PAID")return;const timer=window.setInterval(()=>void refresh(),5000);return()=>window.clearInterval(timer)},[checkout,refresh]);
 if(!checkout)return <div><button type="button" onClick={expired||!resumeExisting?create:()=>void refresh()} disabled={loading} className="flex h-16 w-full items-center justify-center gap-2 rounded-xl border border-blue-200 font-bold text-blue-700 hover:bg-blue-50 disabled:opacity-50">{loading?<LoaderCircle className="size-5 animate-spin"/>:<CreditCard className="size-5"/>}{loading?"Trocando para cartão...":expired?"Gerar novo link de pagamento":resumeExisting?"Continuar crédito":"Crédito"}</button>{error?<p role="alert" className="mt-2 text-xs font-semibold text-red-600">{error}</p>:null}</div>;
 const showQr=async()=>{if(!checkout.hostedPaymentUrl)return;try{setQr(await QRCode.toDataURL(checkout.hostedPaymentUrl,{width:240,margin:1,errorCorrectionLevel:"M"}))}catch{setError("Não foi possível gerar o QR Code.")}};
 return <section className="space-y-4 rounded-2xl border border-blue-200 bg-blue-50/50 p-5 sm:col-span-3"><div className="flex flex-wrap justify-between gap-3"><div><h3 className="text-lg font-bold">Pagamento com cartão de crédito</h3><p className="text-2xl font-bold text-blue-700">{money(checkout.amount)}</p><p className="mt-1 text-sm text-slate-600">Os dados do cartão são informados somente no ambiente seguro do Asaas.</p></div><span className="h-fit rounded-full bg-amber-100 px-3 py-1 text-xs font-bold text-amber-800">{checkout.state==="PAID"?"Pago":"Aguardando pagamento"}</span></div>{checkout.hostedPaymentUrl&&checkout.state!=="PAID"?<div className="grid gap-3 sm:grid-cols-2"><a href={checkout.hostedPaymentUrl} target="_blank" rel="noopener noreferrer" className="flex h-12 items-center justify-center gap-2 rounded-xl bg-blue-600 font-bold text-white"><ExternalLink className="size-4"/>Abrir pagamento seguro</a><button type="button" onClick={()=>void showQr()} className="flex h-12 items-center justify-center gap-2 rounded-xl border bg-white font-bold text-blue-700"><QrCode className="size-4"/>Mostrar QR para celular</button></div>:null}{qr?<div className="grid place-items-center rounded-xl border bg-white p-4"><Image unoptimized src={qr} alt="QR Code contendo somente a URL do checkout Asaas" width={240} height={240}/><p className="mt-2 text-xs text-slate-500">Este QR contém somente o link seguro do checkout.</p></div>:null}<p className="text-xs text-slate-500">Validade: {checkout.expiresAt?new Date(checkout.expiresAt).toLocaleString("pt-BR"):"informada pelo Asaas"}</p><button type="button" onClick={()=>void refresh()} disabled={loading} className="flex h-10 w-full items-center justify-center gap-2 rounded-xl border bg-white text-sm font-bold text-blue-600"><RefreshCw className={`size-4 ${loading?"animate-spin":""}`}/>Atualizar estado</button>{error?<p role="alert" className="text-xs font-semibold text-red-600">{error}</p>:null}</section>}
function money(value:number){return new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(value)}
