"use client";
import { useActionState } from "react";
import { claimVehicle,enrollMonthly,type CustomerActionState } from "@/app/cliente/actions";

const initial:CustomerActionState={};
export function AddCustomerVehicleForm(){const[state,action,pending]=useActionState(claimVehicle,initial);return <form action={action} className="space-y-3 rounded-2xl border bg-white p-5"><h2 className="text-lg font-bold">Adicionar veículo</h2><label className="block text-sm font-semibold">Placa<input name="plate" required maxLength={8} autoCapitalize="characters" placeholder="ABC1D23" className="input uppercase"/></label><label className="block text-sm font-semibold">Tipo<select name="vehicleType" required className="input"><option value="CAR">Carro</option><option value="MOTORCYCLE">Moto</option></select></label>{state.error||state.success?<p role="status" className={`text-sm font-semibold ${state.error?"text-red-600":"text-emerald-700"}`}>{state.error??state.success}</p>:null}<button disabled={pending} className="h-11 w-full rounded-xl bg-blue-600 font-bold text-white disabled:opacity-50">{pending?"Vinculando...":"Adicionar veículo"}</button></form>}

export type SelfServicePlan={plan_id:string;unit_name:string;plan_name:string;description:string|null;price:number;due_day:number;grace_days:number;max_vehicles:number};
export function MonthlyEnrollmentForm({plans,vehicles}:{plans:SelfServicePlan[];vehicles:Array<{id:string;plate:string}>}){const[state,action,pending]=useActionState(enrollMonthly,initial);return <form action={action} className="space-y-4 rounded-2xl border bg-white p-5"><div><h2 className="text-xl font-bold">Tornar-me mensalista</h2><p className="text-sm text-slate-500">A cobertura será ativada somente depois da confirmação do pagamento.</p></div><label className="block text-sm font-semibold">Plano<select name="planId" required className="input"><option value="">Selecione</option>{plans.map(plan=><option key={plan.plan_id} value={plan.plan_id}>{plan.unit_name} · {plan.plan_name} · {new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(plan.price)}/mês</option>)}</select></label><label className="block text-sm font-semibold">Veículo<select name="vehicleId" required className="input"><option value="">Selecione</option>{vehicles.map(vehicle=><option key={vehicle.id} value={vehicle.id}>{vehicle.plate}</option>)}</select></label><label className="flex gap-2 text-sm"><input type="checkbox" name="accepted" value="yes" required/><span>Aceito o preço, vencimento e período de carência apresentados no plano.</span></label>{state.error||state.success?<p role="status" className={`text-sm font-semibold ${state.error?"text-red-600":"text-emerald-700"}`}>{state.error??state.success}</p>:null}<button disabled={pending||!plans.length||!vehicles.length} className="h-12 w-full rounded-xl bg-blue-600 font-bold text-white disabled:opacity-50">{pending?"Criando adesão...":"Assinar e seguir para pagamento"}</button></form>}
