"use client";
import { useActionState } from "react";
import { Banknote,CreditCard,LoaderCircle } from "lucide-react";
import { completeExit,recordPayment,startExit,type OperatorActionState } from "@/app/frentista/actions";
const initial:OperatorActionState={};
export function StartExitForm({sessionId}:{sessionId:string}){const[state,action,pending]=useActionState(startExit,initial);return <FormShell state={state}><form action={action}><input type="hidden" name="sessionId" value={sessionId}/><button disabled={pending} className="h-12 w-full rounded-xl bg-blue-600 font-bold text-white disabled:opacity-50">{pending?"Calculando...":"Iniciar saída e fixar cobrança"}</button></form></FormShell>}
export function CompleteExitForm({sessionId}:{sessionId:string}){const[state,action,pending]=useActionState(completeExit,initial);return <FormShell state={state}><form action={action}><input type="hidden" name="sessionId" value={sessionId}/><button disabled={pending} className="h-12 w-full rounded-xl bg-emerald-600 font-bold text-white disabled:opacity-50">{pending?"Liberando...":"Liberar saída"}</button></form></FormShell>}
export function PaymentForm({sessionId,method}:{sessionId:string;method:"CARD"|"CASH"}){const[state,action,pending]=useActionState(recordPayment,initial);const Icon=method==="CARD"?CreditCard:Banknote;return <FormShell state={state}><form action={action}><input type="hidden" name="sessionId" value={sessionId}/><input type="hidden" name="method" value={method}/><button disabled={pending} className="flex h-16 w-full items-center justify-center gap-2 rounded-xl border font-bold text-blue-600 hover:bg-blue-50 disabled:opacity-50">{pending?<LoaderCircle className="size-5 animate-spin"/>:<Icon className="size-5"/>}{method==="CARD"?"Cartão":"Dinheiro"}</button></form></FormShell>}
function FormShell({state,children}:{state:OperatorActionState;children:React.ReactNode}){return <div>{children}{(state.error||state.success)&&<p role="status" className={`mt-2 text-xs font-semibold ${state.error?"text-red-600":"text-emerald-600"}`}>{state.error??state.success}</p>}</div>}
