import { Banknote,CheckCircle2,CreditCard,Plus,Sparkles,Trophy } from "lucide-react";
import { DashboardShell } from "@/components/dashboard-shell";
import { CloseShiftForm,OpenShiftForm } from "@/components/cash-shift-forms";
import { formatDateTime,formatMoney,getOperatorDashboard } from "@/lib/operator-data";
import { operatorNav } from "@/lib/operator-nav";
export const dynamic="force-dynamic";

type CashPageProps={searchParams:Promise<{opened?:string;closed?:string}>};

export default async function CashPage({searchParams}:CashPageProps){
 const params=await searchParams;
 const data=await getOperatorDashboard();
 const shift=data.open_shift;
 if(!shift)return <DashboardShell nav={operatorNav} active="Caixa" role="Frentista"><div className="mx-auto max-w-5xl space-y-5"><div><h1 className="text-3xl font-bold">Caixa do turno</h1><p className="text-sm text-slate-500">Caixa não aberto. Nenhum valor de turno anterior é exibido.</p></div>{params.closed==="1"?<MotivationalBanner type="closed"/>:<MotivationalBanner type="ready"/>}<section className="mx-auto max-w-md rounded-2xl border bg-white p-6"><h2 className="text-xl font-bold">Abrir caixa</h2><p className="mb-5 mt-1 text-sm text-slate-500">Informe apenas o saldo inicial em dinheiro físico.</p><OpenShiftForm/></section></div></DashboardShell>;
 const expected=Number(shift.opening_amount)+Number(shift.cash_total);
 return <DashboardShell nav={operatorNav} active="Caixa" role="Frentista"><div className="mx-auto max-w-5xl space-y-5"><div><h1 className="text-3xl font-bold">Caixa do turno</h1><p className="text-sm text-slate-500">Turno aberto em {formatDateTime(shift.opened_at,data.unit.timezone)}. Valores restritos à operação atual.</p></div>{params.opened==="1"?<MotivationalBanner type="opened"/>:null}<div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Card label="Saldo inicial" value={formatMoney(shift.opening_amount)}/><Card label="Dinheiro recebido" value={formatMoney(shift.cash_total)}/><Card label="Cartão manual" value={formatMoney(shift.card_total)}/><Card label="PIX confirmado" value={formatMoney(shift.pix_total)} note="Integração indisponível"/></div><div className="grid gap-4 lg:grid-cols-[1fr_420px]"><section className="rounded-2xl border bg-white p-5 sm:p-6"><h2 className="font-bold">Dinheiro físico esperado</h2><div className="mt-5 space-y-3 rounded-2xl bg-slate-50 p-4"><MoneyLine icon={Banknote} label="Saldo inicial" value={shift.opening_amount}/><MoneyLine icon={Plus} label="Dinheiro recebido" value={shift.cash_total}/><div className="border-t pt-4"><p className="text-sm text-slate-500">Dinheiro esperado</p><p className="mt-1 text-3xl font-bold text-emerald-600">{formatMoney(expected)}</p></div></div><div className="mt-4 flex items-center gap-3 rounded-xl border p-4"><CreditCard className="size-5 text-blue-600"/><div><p className="text-sm font-semibold">Cartão não compõe o dinheiro físico</p><p className="text-xs text-slate-500">{formatMoney(shift.card_total)} confirmado manualmente no turno.</p></div></div><p className="mt-4 text-sm"><b>{shift.payment_count}</b> pagamentos confirmados</p></section><section className="rounded-2xl border bg-white p-5 sm:p-6"><h2 className="mb-2 font-bold">Fechar caixa</h2><p className="mb-4 text-xs leading-5 text-slate-500">Conte apenas o dinheiro físico. Se houver diferença, a observação será obrigatória.</p><CloseShiftForm shiftId={shift.id} expectedAmount={expected}/></section></div></div></DashboardShell>;
}

function MotivationalBanner({type}:{type:"ready"|"opened"|"closed"}){
 if(type==="opened")return <section className="rounded-2xl border border-emerald-200 bg-emerald-50 p-5 sm:p-6"><div className="flex items-start gap-4"><span className="flex size-12 shrink-0 items-center justify-center rounded-2xl bg-white text-emerald-600 shadow-sm"><Sparkles className="size-6"/></span><div><p className="text-lg font-bold text-slate-950">Caixa aberto com sucesso! Bom turno! ✨</p><p className="mt-1 text-sm leading-6 text-slate-600">Mais um turno começou. Atendimento de qualidade, organização e atenção fazem a diferença todos os dias.</p><p className="mt-2 text-sm font-semibold text-emerald-700">Vamos fazer acontecer! 🚀</p></div></div></section>;
 if(type==="closed")return <section className="rounded-2xl border border-emerald-200 bg-emerald-50 p-5 sm:p-6"><div className="flex items-start gap-4"><span className="flex size-12 shrink-0 items-center justify-center rounded-2xl bg-white text-emerald-600 shadow-sm"><CheckCircle2 className="size-6"/></span><div><p className="text-lg font-bold text-slate-950">Caixa fechado com sucesso! 🎉</p><p className="mt-1 text-sm leading-6 text-slate-600">Mais um turno concluído. Obrigado pela atenção, organização e cuidado com cada atendimento.</p><p className="mt-2 flex items-center gap-2 text-sm font-semibold text-emerald-700"><Trophy className="size-4"/>Ótimo trabalho hoje. Descanse bem e até o próximo turno! 👏</p></div></div></section>;
 return <section className="rounded-2xl border border-blue-100 bg-blue-50/70 p-5 sm:p-6"><div className="flex items-start gap-4"><span className="flex size-12 shrink-0 items-center justify-center rounded-2xl bg-white text-blue-600 shadow-sm"><Sparkles className="size-6"/></span><div><p className="text-lg font-bold text-slate-950">Pronto para começar um novo turno?</p><p className="mt-1 text-sm leading-6 text-slate-600">Abra o caixa com atenção e comece o dia com foco, organização e um ótimo atendimento.</p><p className="mt-2 text-sm font-semibold text-blue-700">Que seja um turno de conquistas! 💪</p></div></div></section>;
}

function Card({label,value,note}:{label:string;value:string;note?:string}){return <div className="rounded-2xl border bg-white p-5"><p className="text-xs text-slate-500">{label}</p><p className="mt-2 text-xl font-bold">{value}</p>{note?<p className="mt-2 text-[11px] text-slate-400">{note}</p>:null}</div>}
function MoneyLine({icon:Icon,label,value}:{icon:typeof Banknote;label:string;value:number}){return <div className="flex items-center justify-between gap-4"><span className="flex items-center gap-2 text-sm text-slate-600"><Icon className="size-4"/>{label}</span><b>{formatMoney(value)}</b></div>}
