"use server";
import { revalidatePath } from "next/cache";
import { createClient } from "@/lib/supabase/server";
import { getOperatorContext } from "@/lib/operator-data";
export type OperatorActionState = { error?:string; success?:string; sessionId?:string };
function humanError(message:string):string {
  const errors:Record<string,string>={PARKING_FULL:"O pátio atingiu a capacidade máxima. Não é possível registrar outra entrada.",INVALID_PLATE:"Informe uma placa brasileira válida.",NO_ACTIVE_TARIFF:"Esta unidade não possui uma tarifa ativa configurada para este veículo.",ACTIVE_SESSION_EXISTS:"Este veículo já possui uma estadia ativa.",CASH_SHIFT_REQUIRED:"Abra o caixa do turno antes de registrar pagamentos.",PIX_PROVIDER_NOT_CONFIGURED:"PIX integrado ainda não configurado.",PAYMENT_REQUIRED:"O pagamento precisa estar confirmado antes da saída.",EXIT_NOT_STARTED:"Inicie a saída antes de registrar o pagamento.",INVALID_SESSION_STATE:"Esta operação não é permitida no estado atual.",SHIFT_NOT_OPEN:"Este caixa não está aberto.",INVALID_AMOUNT:"Informe um valor válido.",OPERATOR_FORBIDDEN:"Você não possui permissão operacional nesta unidade."};
  return Object.entries(errors).find(([key])=>message.includes(key))?.[1] ?? "Não foi possível concluir a operação. Tente novamente.";
}
function refresh() { ["/frentista","/frentista/entradas","/frentista/saidas","/frentista/veiculos","/frentista/pagamentos","/frentista/caixa"].forEach((path)=>revalidatePath(path)); }
export async function registerEntry(_:OperatorActionState,formData:FormData):Promise<OperatorActionState>{
  const plate=String(formData.get("plate")??"").toUpperCase().replace(/[^A-Z0-9]/g,"").slice(0,7); const vehicleType=String(formData.get("vehicleType")??"CAR");
  if(!/^[A-Z]{3}[0-9][A-Z0-9][0-9]{2}$/.test(plate)) return{error:"Informe uma placa brasileira válida."};
  const {unitId}=await getOperatorContext(); const supabase=await createClient(); const {data,error}=await supabase.rpc("register_parking_entry",{target_unit:unitId,raw_plate:plate,target_vehicle_type:vehicleType});
  if(error)return{error:humanError(error.message)}; refresh(); return{success:`Entrada de ${plate} registrada.`,sessionId:String(data)};
}
export async function startExit(_:OperatorActionState,formData:FormData):Promise<OperatorActionState>{const id=String(formData.get("sessionId")??""); await getOperatorContext(); const supabase=await createClient(); const{error}=await supabase.rpc("start_parking_exit",{session_id:id});if(error)return{error:humanError(error.message)};refresh();return{success:"Saída iniciada. Cobrança calculada."};}
export async function recordPayment(_:OperatorActionState,formData:FormData):Promise<OperatorActionState>{const id=String(formData.get("sessionId")??"");const method=String(formData.get("method")??"");await getOperatorContext();const supabase=await createClient();const{error}=await supabase.rpc("record_manual_payment",{session_id:id,payment_method:method,request_key:crypto.randomUUID()});if(error)return{error:humanError(error.message)};refresh();return{success:"Pagamento registrado."};}
export async function completeExit(_:OperatorActionState,formData:FormData):Promise<OperatorActionState>{const id=String(formData.get("sessionId")??"");await getOperatorContext();const supabase=await createClient();const{error}=await supabase.rpc("complete_parking_exit",{session_id:id});if(error)return{error:humanError(error.message)};refresh();return{success:"Saída liberada."};}
export async function openShift(_:OperatorActionState,formData:FormData):Promise<OperatorActionState>{const amount=Number(String(formData.get("openingAmount")??"0").replace(",","."));if(!Number.isFinite(amount)||amount<0)return{error:"Informe um saldo inicial válido."};const{unitId}=await getOperatorContext();const supabase=await createClient();const{error}=await supabase.rpc("open_cash_shift",{target_unit:unitId,initial_amount:amount});if(error)return{error:humanError(error.message)};refresh();return{success:"Caixa aberto com sucesso."};}
export async function closeShift(_:OperatorActionState,formData:FormData):Promise<OperatorActionState>{const shiftId=String(formData.get("shiftId")??"");const amount=Number(String(formData.get("declaredAmount")??"").replace(",","."));if(!Number.isFinite(amount)||amount<0)return{error:"Informe o dinheiro contado."};await getOperatorContext();const supabase=await createClient();const{data,error}=await supabase.rpc("close_cash_shift",{shift_id:shiftId,declared_amount:amount,closing_notes:String(formData.get("notes")??"")||null});if(error)return{error:humanError(error.message)};refresh();return{success:`Caixa fechado. Diferença: ${new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(Number(data))}.`};}
