import { ArrowRight,Banknote,CarFront,CircleDollarSign,Clock3,CreditCard,Gauge,HandCoins,Home,LogIn,LogOut,Settings,Users } from "lucide-react";
import { DashboardShell,DemoNotice,type NavItem } from "@/components/dashboard-shell";
import { ActionButton } from "@/components/action-button";
import { EntryForm } from "@/components/entry-form";
import { MetricCard,StatusPill } from "@/components/dashboard-parts";
const nav:NavItem[]=[{label:"Painel",href:"/frentista",icon:Home},{label:"Entradas",href:"/frentista/entradas",icon:LogIn},{label:"Saídas",href:"/frentista/saidas",icon:LogOut},{label:"Veículos",href:"/frentista/veiculos",icon:CarFront},{label:"Mensalistas",href:"/frentista/mensalistas",icon:Users},{label:"Pagamentos",href:"/frentista/pagamentos",icon:CreditCard},{label:"Configurações",href:"/frentista/configuracoes",icon:Settings}];
const vehicles=[["ABC1D23","08:15","2h 35m"],["FJG8H45","09:02","1h 48m"],["KLM9N01","07:45","3h 05m"],["QRS2T34","10:10","0h 40m"],["UVW5X67","06:50","3h 58m"]];
const payments=[["ABC1D23","R$ 12,00","Aguardando PIX"],["FJG8H45","R$ 9,00","Pago"],["KLM9N01","R$ 18,00","Dinheiro"],["QRS2T34","R$ 6,00","Aguardando PIX"]];
export default function OperatorPage(){return <DashboardShell nav={nav} active="Painel" role="Frentista" aside={<div className="rounded-2xl border bg-white p-4 shadow-sm"><div className="flex justify-between text-sm font-bold">Caixa do turno<ArrowRight className="size-4"/></div><p className="mt-4 text-xs text-slate-500">Saldo demonstrativo</p><p className="mt-1 text-xl font-bold text-emerald-600">R$ 1.245,60</p><ActionButton className="mt-4 w-full rounded-lg border py-2 text-xs font-semibold">Ver detalhes</ActionButton></div>}><div className="mx-auto max-w-[1400px] space-y-5">
<div className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-3xl font-bold">Painel do Frentista</h1><p className="mt-1 text-sm text-slate-500">Gerencie entradas, sa&iacute;das e pagamentos do estacionamento.</p></div><DemoNotice/></div>
<EntryForm/>
<div id="atalhos" className="scroll-mt-24 grid grid-cols-2 gap-3 sm:grid-cols-3 xl:grid-cols-5">{[["Saída",LogOut],["Veículos no pátio",CarFront],["Caixa",HandCoins],["Mensalistas",Users],["Pagamentos PIX",CircleDollarSign]].map(([label,Icon])=><ActionButton key={label as string} className="flex h-14 items-center justify-center gap-2 rounded-xl border bg-white text-sm font-semibold text-blue-600 shadow-sm"><Icon className="size-5"/>{label as string}</ActionButton>)}</div>
<div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Veículos no pátio" value="42" icon={CarFront}/><MetricCard label="Vagas disponíveis" value="58" icon={Gauge} tone="green"/><MetricCard label="Entradas hoje" value="86" icon={LogIn} tone="violet"/><MetricCard label="Saídas hoje" value="44" icon={LogOut} tone="orange"/></div>
<div id="operacao" className="scroll-mt-24 grid gap-4 xl:grid-cols-[1.25fr_.82fr_.95fr]"><section id="veiculos" className="scroll-mt-24 overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="border-b px-5 py-4 font-bold">Ve&iacute;culos no p&aacute;tio</div><table className="w-full text-left text-xs"><thead className="bg-slate-50 text-slate-500"><tr><th className="px-5 py-3">Placa</th><th>Entrada</th><th>Tempo</th><th>Status</th></tr></thead><tbody>{vehicles.map((v,i)=><tr key={v[0]} className={i===0?"bg-blue-50":"border-t"}><td className="px-5 py-3 font-semibold text-blue-600">{v[0]}</td><td>{v[1]}</td><td>{v[2]}</td><td><StatusPill>Ativo</StatusPill></td></tr>)}</tbody></table><ActionButton className="m-4 text-xs font-semibold text-blue-600">Ver todos os ve&iacute;culos &rarr;</ActionButton></section>
<section className="rounded-2xl border bg-white p-5 shadow-xl"><div className="flex gap-3"><span className="grid size-11 place-items-center rounded-xl bg-blue-50 text-blue-600"><CarFront className="size-5"/></span><div><h2 className="text-xl font-bold">ABC1D23</h2><p className="text-xs text-slate-500">Entrada: Hoje 08:15</p></div></div><div className="my-5 h-px bg-slate-200"/><div className="space-y-4"><div className="flex gap-3"><Clock3 className="size-5"/><div><p className="text-xs text-slate-500">Perman&ecirc;ncia</p><p className="text-xl font-bold">2h 35m</p></div></div><div className="flex gap-3"><CircleDollarSign className="size-5 text-emerald-600"/><div><p className="text-xs text-slate-500">Valor atual</p><p className="text-xl font-bold">R$ 12,00</p></div></div></div><p className="mt-6 text-xs font-semibold">Registrar pagamento</p><div className="mt-2 grid grid-cols-3 gap-2">{[["PIX",CircleDollarSign],["Cartão",CreditCard],["Dinheiro",Banknote]].map(([l,I])=><ActionButton key={l as string} className="flex flex-col items-center gap-2 rounded-xl border p-3 text-xs font-semibold text-blue-600"><I className="size-5"/>{l as string}</ActionButton>)}</div></section>
<section id="pagamentos" className="scroll-mt-24 rounded-2xl border bg-white p-5"><div className="flex justify-between"><h2 className="font-bold">Pagamentos</h2><span className="text-xs text-blue-600">Ver todos</span></div><div className="mt-4">{payments.map((p,i)=><div key={p[0]} className="flex items-center gap-3 border-b py-3"><span className="grid size-9 place-items-center rounded-xl bg-slate-50">{i%2?<CircleDollarSign className="size-4 text-emerald-600"/>:<Clock3 className="size-4 text-amber-600"/>}</span><div className="flex-1"><p className="text-sm font-semibold">{p[0]}</p><p className="text-xs text-slate-500">{p[1]}</p></div><StatusPill tone={i%2?"green":"amber"}>{p[2]}</StatusPill></div>)}</div><ActionButton className="mt-4 w-full rounded-xl border border-blue-500 py-2.5 text-xs font-semibold text-blue-600">Abrir tela de pagamentos</ActionButton></section></div>
</div></DashboardShell>}






