"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { requireMonthlyUnit } from "@/lib/monthly-admin";
import { createClient } from "@/lib/supabase/server";

const text=(form:FormData,key:string)=>String(form.get(key)??"").trim();
const num=(form:FormData,key:string)=>Number(text(form,key).replace(",","."));
const fail=(message:string,path:string):never=>redirect(`${path}?erro=${encodeURIComponent(message)}`);
function friendly(message:string){if(message.includes("MONTHLY_ADMIN_FORBIDDEN")||message.includes("MONTHLY_FORBIDDEN"))return"Você não tem permissão para administrar mensalistas nesta unidade.";if(message.includes("MONTHLY_PLAN_UNAVAILABLE"))return"O plano selecionado não está disponível.";if(message.includes("MONTHLY_CUSTOMER_NOT_FOUND"))return"Cliente não encontrado ou inativo.";if(message.includes("one_live_customer"))return"Este cliente já possui uma assinatura ativa ou suspensa nesta unidade.";if(message.includes("MONTHLY_VEHICLE_CUSTOMER_MISMATCH"))return"O veículo não pertence ao cliente desta assinatura.";if(message.includes("MONTHLY_MAX_VEHICLES_REACHED"))return"O limite de veículos do plano foi atingido.";if(message.includes("MONTHLY_INVALID_STATUS_TRANSITION"))return"Esta alteração de status não é permitida.";return"Não foi possível concluir a operação com segurança.";}

export async function createPlan(form:FormData){const path="/ceo/mensalistas/planos",unitId=text(form,"unitId");try{await requireMonthlyUnit(unitId,true);const input={name:text(form,"name"),description:text(form,"description"),price:num(form,"price"),dueDay:num(form,"dueDay"),graceDays:num(form,"graceDays"),maxVehicles:num(form,"maxVehicles")};if(input.name.length<2||input.price<=0||input.dueDay<1||input.dueDay>31||input.graceDays<0||input.graceDays>90||input.maxVehicles<1)fail("Revise os dados do plano.",path);const supabase=await createClient();const{error}=await supabase.rpc("create_monthly_plan",{target_unit:unitId,plan_name:input.name,plan_description:input.description,plan_price:input.price,plan_due_day:input.dueDay,plan_grace_days:input.graceDays,plan_max_vehicles:input.maxVehicles});if(error)fail(friendly(error.message),path);}catch(error){fail(friendly(error instanceof Error?error.message:""),path);}revalidatePath(path);redirect(`${path}?sucesso=Plano criado`);}
export async function togglePlan(form:FormData){const path="/ceo/mensalistas/planos",unitId=text(form,"unitId");try{await requireMonthlyUnit(unitId,true);const supabase=await createClient();const{error}=await supabase.rpc("set_monthly_plan_enabled",{target_plan:text(form,"planId"),target_enabled:text(form,"enabled")==="true"});if(error)fail(friendly(error.message),path);}catch(error){fail(friendly(error instanceof Error?error.message:""),path);}revalidatePath(path);redirect(`${path}?sucesso=Plano atualizado`);}
export async function createSubscription(form:FormData){const path="/ceo/mensalistas/nova",unitId=text(form,"unitId");let id="";try{await requireMonthlyUnit(unitId,true);const supabase=await createClient();const{data,error}=await supabase.rpc("create_monthly_subscription",{target_unit:unitId,target_customer:text(form,"customerId"),target_plan:text(form,"planId"),target_starts_on:text(form,"startsOn"),override_due_day:null,override_grace_days:null,override_price:null});if(error)fail(friendly(error.message),path);id=String(data);const vehicleId=text(form,"vehicleId");if(vehicleId){const linked=await supabase.rpc("attach_monthly_vehicle",{target_subscription:id,target_vehicle:vehicleId,target_valid_from:text(form,"startsOn")});if(linked.error)fail(friendly(linked.error.message),`/ceo/mensalistas/${id}`);}}catch(error){fail(friendly(error instanceof Error?error.message:""),path);}revalidatePath("/ceo/mensalistas");redirect(`/ceo/mensalistas/${id}?sucesso=Assinatura criada`);}
export async function changeSubscriptionStatus(form:FormData){const id=text(form,"subscriptionId"),path=`/ceo/mensalistas/${id}`,unitId=text(form,"unitId");try{await requireMonthlyUnit(unitId,true);const supabase=await createClient();const{error}=await supabase.rpc("set_monthly_subscription_status",{target_subscription:id,target_status:text(form,"status"),reason:text(form,"reason"),effective_at_period_end:text(form,"atPeriodEnd")==="true"});if(error)fail(friendly(error.message),path);}catch(error){fail(friendly(error instanceof Error?error.message:""),path);}revalidatePath(path);revalidatePath("/ceo/mensalistas");redirect(`${path}?sucesso=Status atualizado`);}
export async function attachVehicle(form:FormData){const id=text(form,"subscriptionId"),path=`/ceo/mensalistas/${id}`,unitId=text(form,"unitId");try{await requireMonthlyUnit(unitId,true);const supabase=await createClient();const{error}=await supabase.rpc("attach_monthly_vehicle",{target_subscription:id,target_vehicle:text(form,"vehicleId"),target_valid_from:text(form,"validFrom")});if(error)fail(friendly(error.message),path);}catch(error){fail(friendly(error instanceof Error?error.message:""),path);}revalidatePath(path);redirect(`${path}?sucesso=Veículo vinculado`);}
export async function detachVehicle(form:FormData){const id=text(form,"subscriptionId"),path=`/ceo/mensalistas/${id}`,unitId=text(form,"unitId");try{await requireMonthlyUnit(unitId,true);const supabase=await createClient();const{error}=await supabase.rpc("detach_monthly_vehicle",{target_link:text(form,"linkId"),target_valid_until:new Date().toISOString().slice(0,10)});if(error)fail(friendly(error.message),path);}catch(error){fail(friendly(error instanceof Error?error.message:""),path);}revalidatePath(path);redirect(`${path}?sucesso=Veículo desvinculado`);}
export async function generatePeriod(form:FormData){const id=text(form,"subscriptionId"),path=`/ceo/mensalistas/${id}`,unitId=text(form,"unitId");try{await requireMonthlyUnit(unitId,true);const supabase=await createClient();const{error}=await supabase.rpc("generate_monthly_billing_period",{target_subscription:id,target_year:num(form,"year"),target_month:num(form,"month")});if(error)fail(friendly(error.message),path);}catch(error){fail(friendly(error instanceof Error?error.message:""),path);}revalidatePath(path);redirect(`${path}?sucesso=Competência disponível`);}
