import Link from "next/link";
import { ArrowLeft, CarFront, CircleHelp, FileText, History, LockKeyhole, ParkingSquare } from "lucide-react";
import { notFound } from "next/navigation";
import { logout } from "@/app/login/actions";
import { requireArea } from "@/lib/auth";
import { formatDateTime, formatMoney } from "@/lib/operator-format";
import { createClient } from "@/lib/supabase/server";

const staticSections={saida:{title:"Como funciona a saída",text:"Após a cobrança ser calculada, o pagamento precisa ser confirmado antes da liberação do veículo.",icon:CarFront},ajuda:{title:"Ajuda",text:"Em caso de divergência, informe sua placa e o horário aproximado ao frentista da unidade.",icon:CircleHelp}} as const;
type Session={id:string;plate_snapshot:string;status:string;entered_at:string;exited_at:string|null;final_amount:number|null;parking_units:{name:string;timezone:string}|null;payments:{id:string;amount:number;method:string;status:string;paid_at:string|null}[]};
export default async function ClientSection({params}:{params:Promise<{secao:string}>}){const{secao}=await params;if(!["historico","recibos","saida","ajuda"].includes(secao))notFound();const access=await requireArea("cliente");const supabase=await createClient();const{data:vehicles}=await supabase.from("vehicles").select("id").eq("customer_id",access.user.id);const ids=(vehicles??[]).map(v=>v.id);let rows:Session[]=[];if(ids.length&&(secao==="historico"||secao==="recibos")){let query=supabase.from("parking_sessions").select("id,plate_snapshot,status,entered_at,exited_at,final_amount,parking_units(name,timezone),payments(id,amount,method,status,paid_at)").in("vehicle_id",ids).order("entered_at",{ascending:false}).limit(50);if(secao==="recibos")query=query.eq("status","EXITED").eq("payment_status","PAID");const{data}=await query;rows=(data??[]) as unknown as Session[]}const section=secao==="historico"?{title:"Histórico de estadias",text:"Somente sessões realmente associadas aos seus veículos.",icon:History}:secao==="recibos"?{title:"Recibos",text:"Somente pagamentos reais de sessões finalizadas.",icon:FileText}:staticSections[secao as keyof typeof staticSections];const Icon=section.icon;return <main className="min-h-screen bg-slate-100 px-3 py-5"><div className="mx-auto max-w-[620px] overflow-hidden rounded-[28px] border bg-white shadow-2xl"><header className="flex h-20 items-center justify-between border-b px-5"><Link href="/cliente" className="flex items-center gap-3 font-bold"><span className="grid size-10 place-items-center rounded-xl bg-blue-600 text-white"><ParkingSquare className="size-5"/></span>Star Carvalhos</Link><form action={logout}><button className="rounded-xl border px-3 py-2 text-xs font-semibold">Sair</button></form></header><div className="space-y-5 p-5"><Link href="/cliente" className="inline-flex items-center gap-2 text-sm font-semibold text-blue-600"><ArrowLeft className="size-4"/>Painel do cliente</Link><section className="rounded-3xl bg-gradient-to-br from-blue-600 to-indigo-700 p-6 text-white"><Icon className="size-8"/><h1 className="mt-5 text-2xl font-bold">{section.title}</h1><p className="mt-2 text-sm text-blue-100">{section.text}</p></section>{secao==="historico"||secao==="recibos"?<RealRows rows={rows} receipts={secao==="recibos"}/>:<section className="rounded-2xl border bg-slate-50 p-5 text-sm leading-6 text-slate-600">{section.text}</section>}<p className="flex items-center justify-center gap-2 py-3 text-[11px] text-slate-400"><LockKeyhole className="size-3"/>Área exclusiva do cliente autenticado.</p></div></div></main>}
function RealRows({rows,receipts}:{rows:Session[];receipts:boolean}){if(!rows.length)return <p className="rounded-2xl border border-dashed p-10 text-center text-sm text-slate-500">{receipts?"Você ainda não possui recibos de pagamentos confirmados.":"Você ainda não possui histórico de estadias."}</p>;return <div className="space-y-3">{rows.map(row=>{const tz=row.parking_units?.timezone??"America/Bahia";const payment=row.payments.find(p=>p.status==="PAID");return <article key={row.id} className="rounded-2xl border p-4"><div className="flex justify-between"><b>{row.plate_snapshot}</b><span className="text-xs text-slate-500">{row.status}</span></div><p className="mt-2 text-xs text-slate-500">Entrada: {formatDateTime(row.entered_at,tz)}{row.exited_at?` · Saída: ${formatDateTime(row.exited_at,tz)}`:""}</p>{payment?<p className="mt-2 text-sm font-semibold">{formatMoney(payment.amount)} · {payment.method==="CASH"?"Dinheiro":payment.method==="CARD"?"Cartão — confirmação manual":"PIX"}</p>:<p className="mt-2 text-xs text-slate-500">Nenhum pagamento confirmado.</p>}</article>})}</div>}

