import Link from "next/link";
import { Search } from "lucide-react";
import { DashboardShell } from "@/components/dashboard-shell";
import { getOperatorContext } from "@/lib/operator-data";
import { formatDateTime, formatDuration, formatMoney } from "@/lib/operator-format";
import { operatorNav } from "@/lib/operator-nav";
import { createClient } from "@/lib/supabase/server";
import { serverNow } from "@/lib/server-time";

export const dynamic = "force-dynamic";
const PAGE_SIZE = 25;
type HistoryRow = { id:string; plate_snapshot:string; vehicle_type:"CAR"|"MOTORCYCLE"; status:string; entered_at:string; exited_at:string|null; final_amount:number|null; calculated_amount:number|null; payment_status:string; tariff_snapshot:{name?:string;version_number?:number}|null; parking_units:{name:string;timezone:string}|null; payments:{method:string;status:string;paid_at:string|null;manual_confirmation:boolean;received_by:string|null}[]; entry_operator_id:string; exit_operator_id:string|null };

export default async function HistoryPage({searchParams}:{searchParams:Promise<{q?:string;period?:string;status?:string;page?:string;session?:string}>}) {
  const params=await searchParams; const {unitId}=await getOperatorContext(); const supabase=await createClient();
  const page=Math.max(1,Number.parseInt(params.page??"1",10)||1); const period=["1","7","30"].includes(params.period??"")?Number(params.period):30;
  const status=params.status??"closed"; const plate=(params.q??"").toUpperCase().replace(/[^A-Z0-9]/g,"").slice(0,7);
  const now=serverNow(); const since=new Date(now-period*86400000).toISOString();
  let query=supabase.from("parking_sessions").select("id,plate_snapshot,vehicle_type,status,entered_at,exited_at,final_amount,calculated_amount,payment_status,tariff_snapshot,entry_operator_id,exit_operator_id,parking_units(name,timezone),payments(method,status,paid_at,manual_confirmation,received_by)",{count:"exact"}).eq("unit_id",unitId).gte("entered_at",since).order("entered_at",{ascending:false});
  if(plate) query=query.ilike("plate_snapshot",`${plate}%`);
  if(status==="closed") query=query.eq("status","EXITED"); else if(status==="paid") query=query.eq("payment_status","PAID"); else if(status==="review") query=query.in("status",["CANCELLED","MANUAL_REVIEW"]);
  const {data,error,count}=await query.range((page-1)*PAGE_SIZE,page*PAGE_SIZE-1); if(error) throw new Error("HISTORY_QUERY_FAILED");
  const rows=(data??[]) as unknown as HistoryRow[]; const ids=[...new Set(rows.flatMap(row=>[row.entry_operator_id,row.exit_operator_id,...row.payments.map(p=>p.received_by)].filter(Boolean) as string[]))];
  const {data:profiles}=ids.length?await supabase.from("profiles").select("id,full_name").in("id",ids):{data:[]}; const names=new Map((profiles??[]).map(p=>[p.id,p.full_name]));
  const selected=rows.find(row=>row.id===params.session); const pages=Math.max(1,Math.ceil((count??0)/PAGE_SIZE));
  return <DashboardShell nav={operatorNav} active="Histórico" role="Frentista"><div className="mx-auto max-w-7xl space-y-5"><div><h1 className="text-3xl font-bold">Histórico operacional</h1><p className="text-sm text-slate-500">Consulta somente leitura das sessões da sua unidade.</p></div>
    <form className="grid gap-3 rounded-2xl border bg-white p-4 md:grid-cols-[1fr_auto_auto_auto]"><label className="flex h-11 items-center gap-2 rounded-xl border px-3"><Search className="size-4 text-slate-400"/><input name="q" defaultValue={plate} placeholder="Buscar por placa" className="min-w-0 flex-1 outline-none"/></label><select name="period" defaultValue={String(period)} className="h-11 rounded-xl border px-3"><option value="1">Hoje</option><option value="7">Últimos 7 dias</option><option value="30">Últimos 30 dias</option></select><select name="status" defaultValue={status} className="h-11 rounded-xl border px-3"><option value="all">Todos</option><option value="closed">Encerrados</option><option value="paid">Pagos</option><option value="review">Cancelados/Revisão</option></select><button className="h-11 rounded-xl bg-blue-600 px-6 font-bold text-white">Buscar</button></form>
    {plate&&rows.length===0?<section className="rounded-2xl border border-amber-200 bg-amber-50 p-5"><h2 className="font-bold text-amber-900">Este veículo não possui estadia ativa nem histórico no período.</h2><p className="mt-1 text-sm text-amber-700">Amplie o período ou confira a placa informada.</p></section>:null}
    <div className="grid gap-4 xl:grid-cols-[1fr_380px]"><section className="overflow-x-auto rounded-2xl border bg-white"><table className="w-full min-w-[950px] text-left text-xs"><thead className="bg-slate-50 text-slate-500"><tr>{["Placa","Tipo","Entrada","Saída","Permanência","Valor","Pagamento","Status","Unidade"].map(h=><th key={h} className="px-4 py-3">{h}</th>)}</tr></thead><tbody>{rows.map(row=>{const payment=row.payments.find(p=>p.status==="PAID");const tz=row.parking_units?.timezone??"America/Bahia";const duration=Math.max(0,Math.round((new Date(row.exited_at??now).getTime()-new Date(row.entered_at).getTime())/60000));return <tr key={row.id} className="border-t hover:bg-slate-50"><td className="px-4 py-3"><Link className="font-bold text-blue-600" href={{query:{...params,session:row.id}}}>{row.plate_snapshot}</Link></td><td>{row.vehicle_type==="CAR"?"Carro":"Moto"}</td><td>{formatDateTime(row.entered_at,tz)}</td><td>{row.exited_at?formatDateTime(row.exited_at,tz):"—"}</td><td>{formatDuration(duration)}</td><td>{formatMoney(row.final_amount??row.calculated_amount)}</td><td>{payment?payment.method==="CASH"?"Dinheiro":payment.method==="CARD"?"Cartão — manual":"PIX":"—"}</td><td>{row.status}</td><td>{row.parking_units?.name??"—"}</td></tr>})}</tbody></table>{rows.length===0&&!plate?<p className="p-10 text-center text-sm text-slate-500">Nenhuma sessão encontrada.</p>:null}<div className="flex items-center justify-between border-t p-4 text-sm"><span>Página {page} de {pages} · {count??0} registros</span><div className="flex gap-2">{page>1?<Link className="rounded-lg border px-3 py-2" href={{query:{...params,page:page-1}}}>Anterior</Link>:null}{page<pages?<Link className="rounded-lg border px-3 py-2" href={{query:{...params,page:page+1}}}>Próxima</Link>:null}</div></div></section>
      <aside className="rounded-2xl border bg-white p-5">{selected?<SessionDetail row={selected} names={names}/>:<div className="grid min-h-56 place-items-center text-center text-sm text-slate-500">Selecione uma placa para ver todos os detalhes.</div>}</aside></div></div></DashboardShell>;
}

function SessionDetail({row,names}:{row:HistoryRow;names:Map<string,string>}){const payment=row.payments.find(p=>p.status==="PAID");const tz=row.parking_units?.timezone??"America/Bahia";const items=[["Placa",row.plate_snapshot],["Tipo",row.vehicle_type==="CAR"?"Carro":"Moto"],["Unidade",row.parking_units?.name??"—"],["Entrada",formatDateTime(row.entered_at,tz)],["Saída",row.exited_at?formatDateTime(row.exited_at,tz):"—"],["Tarifa",row.tariff_snapshot?.name??"—"],["Versão",String(row.tariff_snapshot?.version_number??"—")],["Valor calculado",formatMoney(row.calculated_amount)],["Valor final",formatMoney(row.final_amount)],["Pagamento",payment?.status??row.payment_status],["Método",payment?payment.method==="CASH"?"Dinheiro":payment.method==="CARD"?"Cartão — confirmação manual":"PIX":"—"],["Pago em",payment?.paid_at?formatDateTime(payment.paid_at,tz):"—"],["Operador da entrada",names.get(row.entry_operator_id)??"—"],["Operador da saída",row.exit_operator_id?names.get(row.exit_operator_id)??"—":"—"],["Status final",row.status],["ID da sessão",row.id]];return <><h2 className="text-lg font-bold">Detalhes da sessão</h2><dl className="mt-4 space-y-3">{items.map(([label,value])=><div key={label} className="border-b pb-2"><dt className="text-xs text-slate-500">{label}</dt><dd className="break-all text-sm font-semibold">{value}</dd></div>)}</dl></>}

