import Link from "next/link";
import { CalendarDays, ChevronDown, CircleDollarSign, Clock3, Layers3, Search, ShieldCheck, Tag, UserRound, WalletCards } from "lucide-react";
import { DashboardShell } from "@/components/dashboard-shell";
import { OperationBadge } from "@/components/operation-badge";
import { VehicleGroupIcon, VehicleTypeIcon } from "@/components/vehicle-type-icon";
import { getOperatorContext } from "@/lib/operator-data";
import { formatDateTime, formatDuration, formatMoney, formatPaymentMethod, formatPaymentStatus, formatSessionFinancialStatus, formatVehicleType, sessionParkingStatus } from "@/lib/operator-format";
import { operatorNav } from "@/lib/operator-nav";
import { createClient } from "@/lib/supabase/server";
import { serverNow } from "@/lib/server-time";

export const dynamic = "force-dynamic";
const PAGE_SIZE = 25;
type HistoryRow = { id:string; plate_snapshot:string; vehicle_type:"CAR"|"MOTORCYCLE"; status:string; entered_at:string; exited_at:string|null; final_amount:number|null; calculated_amount:number|null; payment_status:string; entry_mode:string; financial_obligation:string; tariff_snapshot:{name?:string;version_number?:number}|null; parking_units:{name:string;timezone:string}|null; payments:{method:string;status:string;paid_at:string|null;manual_confirmation:boolean;received_by:string|null}[]; entry_operator_id:string; exit_operator_id:string|null };

export default async function HistoryPage({searchParams}:{searchParams:Promise<{q?:string;period?:string;status?:string;page?:string;session?:string}>}) {
  const params=await searchParams; const {unitId}=await getOperatorContext(); const supabase=await createClient();
  const page=Math.max(1,Number.parseInt(params.page??"1",10)||1); const period=["1","7","30"].includes(params.period??"")?Number(params.period):30;
  const status=params.status??"closed"; const plate=(params.q??"").toUpperCase().replace(/[^A-Z0-9]/g,"").slice(0,7);
  const now=serverNow(); const since=new Date(now-period*86400000).toISOString();
  let query=supabase.from("parking_sessions").select("id,plate_snapshot,vehicle_type,status,entered_at,exited_at,final_amount,calculated_amount,payment_status,entry_mode,financial_obligation,tariff_snapshot,entry_operator_id,exit_operator_id,parking_units(name,timezone),payments(method,status,paid_at,manual_confirmation,received_by)",{count:"exact"}).eq("unit_id",unitId).gte("entered_at",since).order("entered_at",{ascending:false});
  if(plate) query=query.ilike("plate_snapshot",`${plate}%`);
  if(status==="closed") query=query.eq("status","EXITED"); else if(status==="paid") query=query.eq("payment_status","PAID"); else if(status==="review") query=query.in("status",["CANCELLED","MANUAL_REVIEW"]);
  const {data,error,count}=await query.range((page-1)*PAGE_SIZE,page*PAGE_SIZE-1); if(error) throw new Error("HISTORY_QUERY_FAILED");
  const rows=(data??[]) as unknown as HistoryRow[]; const ids=[...new Set(rows.flatMap(row=>[row.entry_operator_id,row.exit_operator_id,...row.payments.map(p=>p.received_by)].filter(Boolean) as string[]))];
  const {data:profiles}=ids.length?await supabase.from("profiles").select("id,full_name").in("id",ids):{data:[]}; const names=new Map((profiles??[]).map(p=>[p.id,p.full_name]));
  const selected=rows.find(row=>row.id===params.session); const pages=Math.max(1,Math.ceil((count??0)/PAGE_SIZE));
  return <DashboardShell nav={operatorNav} active="Histórico" role="Frentista"><div className="mx-auto max-w-[1500px] space-y-5"><div><h1 className="text-3xl font-bold">Histórico operacional</h1><p className="text-sm text-slate-500">Consulta somente leitura das sessões da sua unidade.</p></div>
    <form className="grid gap-3 rounded-2xl border bg-white p-4 shadow-sm md:grid-cols-[1fr_auto_auto_auto]"><label className="flex h-12 items-center gap-2 rounded-xl border border-slate-200 px-4 transition focus-within:border-blue-400 focus-within:ring-4 focus-within:ring-blue-50"><Search className="size-4 text-blue-500"/><input name="q" defaultValue={plate} placeholder="Buscar por placa" className="min-w-0 flex-1 bg-transparent outline-none"/></label><select name="period" defaultValue={String(period)} className="h-12 w-full rounded-xl border border-slate-200 bg-white px-4"><option value="1">Hoje</option><option value="7">Últimos 7 dias</option><option value="30">Últimos 30 dias</option></select><select name="status" defaultValue={status} className="h-12 w-full rounded-xl border border-slate-200 bg-white px-4"><option value="all">Todos</option><option value="closed">Encerrados</option><option value="paid">Pagos</option><option value="review">Cancelados/Revisão</option></select><button className="h-12 w-full rounded-xl bg-blue-600 px-6 font-bold text-white shadow-sm transition hover:bg-blue-700">Buscar</button></form>
    {plate&&rows.length===0?<section className="rounded-2xl border border-amber-200 bg-amber-50 p-5"><h2 className="font-bold text-amber-900">Este veículo não possui estadia ativa nem histórico no período.</h2><p className="mt-1 text-sm text-amber-700">Amplie o período ou confira a placa informada.</p></section>:null}
    <div className="grid min-w-0 gap-4 xl:grid-cols-[minmax(0,1fr)_410px]"><section className="min-w-0 overflow-x-auto rounded-2xl border bg-white shadow-sm"><table className="w-full min-w-[900px] table-fixed text-left text-[11px] xl:text-xs"><colgroup><col className="w-[14%]"/><col className="w-[9%]"/><col className="w-[15%]"/><col className="w-[15%]"/><col className="w-[12%]"/><col className="w-[10%]"/><col className="w-[11%]"/><col className="w-[14%]"/></colgroup><thead className="bg-slate-50/90 text-slate-500"><tr>{["Placa","Tipo","Entrada","Saída","Permanência","Valor","Pagamento","Status"].map(h=><th key={h} className="px-2.5 py-3 font-semibold xl:px-3">{h}</th>)}</tr></thead><tbody>{rows.map(row=>{const payment=row.payments.find(p=>p.status==="PAID");const monthly=formatSessionFinancialStatus(row.entry_mode,row.financial_obligation);const tz=row.parking_units?.timezone??"America/Bahia";const duration=Math.max(0,Math.round((new Date(row.exited_at??now).getTime()-new Date(row.entered_at).getTime())/60000));const isSelected=row.id===params.session;return <tr key={row.id} className={`border-t transition ${isSelected?"bg-blue-50/70 shadow-[inset_3px_0_0_#2563eb]":"hover:bg-slate-50"}`}><td className="px-2.5 py-3 xl:px-3"><Link className="inline-flex items-center gap-1.5 font-bold text-slate-900 hover:text-blue-600" href={{query:{...params,session:row.id}}}><VehicleTypeIcon vehicleType={row.vehicle_type} className="size-3.5 shrink-0 text-slate-500"/><span className="truncate">{row.plate_snapshot}</span></Link></td><td className="px-2.5 py-3 xl:px-3">{formatVehicleType(row.vehicle_type)}</td><td className="px-2.5 py-3 xl:px-3"><CompactDateTime value={row.entered_at} timezone={tz}/></td><td className="px-2.5 py-3 xl:px-3">{row.exited_at?<CompactDateTime value={row.exited_at} timezone={tz}/>:"—"}</td><td className="px-2.5 py-3 xl:px-3">{formatDuration(duration)}</td><td className="px-2.5 py-3 font-semibold xl:px-3">{formatMoney(row.final_amount??row.calculated_amount)}</td><td className="px-2.5 py-3 xl:px-3"><span className="block truncate">{monthly?"Mensalidade":payment?formatPaymentMethod(payment.method,payment.manual_confirmation):"—"}</span></td><td className="px-2.5 py-3 xl:px-3"><OperationBadge {...sessionParkingStatus(row.status,row.entry_mode,row.financial_obligation)}/></td></tr>})}</tbody></table>{rows.length===0&&!plate?<p className="p-10 text-center text-sm text-slate-500">Nenhuma sessão encontrada.</p>:null}<div className="flex min-w-[900px] items-center justify-between border-t p-4 text-sm"><span>Página {page} de {pages} · {count??0} registros</span><div className="flex gap-2">{page>1?<Link className="rounded-lg border px-3 py-2" href={{query:{...params,page:page-1}}}>Anterior</Link>:null}{page<pages?<Link className="rounded-lg border px-3 py-2" href={{query:{...params,page:page+1}}}>Próxima</Link>:null}</div></div></section>
      {selected?<aside className="rounded-2xl border bg-white p-3 shadow-sm xl:sticky xl:top-4 xl:self-start"><SessionDetail row={selected} names={names}/></aside>:<aside className="hidden rounded-2xl border bg-white p-3 shadow-sm xl:block xl:sticky xl:top-4 xl:self-start"><div className="grid min-h-64 place-items-center text-center text-sm text-slate-500"><div><VehicleGroupIcon className="mx-auto mb-3 size-9 text-slate-300"/><p>Selecione uma placa para ver todos os detalhes.</p></div></div></aside>}</div></div></DashboardShell>;
}

function CompactDateTime({value,timezone}:{value:string;timezone:string}){const formatted=formatDateTime(value,timezone);const [date,time]=formatted.split(", ");return <span className="leading-4"><span className="block whitespace-nowrap">{date}</span><span className="block whitespace-nowrap text-slate-500">{time??""}</span></span>}

function SessionDetail({row,names}:{row:HistoryRow;names:Map<string,string>}){
  const payment=row.payments.find(p=>p.status==="PAID"); const monthly=formatSessionFinancialStatus(row.entry_mode,row.financial_obligation); const tz=row.parking_units?.timezone??"America/Bahia"; const duration=Math.max(0,Math.round((new Date(row.exited_at??row.entered_at).getTime()-new Date(row.entered_at).getTime())/60000));
  const financialLabel=monthly??formatPaymentStatus(payment?.status??row.payment_status); const entryName=names.get(row.entry_operator_id)??"Não informado"; const exitName=row.exit_operator_id?(names.get(row.exit_operator_id)??"Não informado"):"Não informado"; const isPaid=Boolean(monthly)||payment?.status==="PAID"||row.payment_status==="PAID"; const isFinalized=row.status==="EXITED"; const entryMissing=entryName==="Não informado"; const exitMissing=exitName==="Não informado";
  let diagnostic:{tone:"success"|"warning";text:string};
  if(!isPaid||!isFinalized) diagnostic={tone:"warning",text:"Sessão requer conferência operacional ou financeira."};
  else if(entryMissing&&exitMissing) diagnostic={tone:"warning",text:"Sessão concluída. Operadores de entrada e saída não identificados no histórico."};
  else if(entryMissing) diagnostic={tone:"warning",text:"Sessão concluída. Operador de entrada não identificado no histórico."};
  else if(exitMissing) diagnostic={tone:"warning",text:"Sessão concluída. Operador de saída não identificado no histórico."};
  else diagnostic={tone:"success",text:"Operação concluída sem divergências."};
  return <div><h2 className="px-1 text-lg font-bold">Detalhes da sessão</h2>
    <div className="mt-3 rounded-2xl border border-slate-200 bg-white p-3"><div className="flex flex-wrap items-start justify-between gap-2.5"><div className="flex min-w-0 items-center gap-3"><span className="grid size-11 shrink-0 place-items-center rounded-xl bg-blue-600 text-white shadow-sm"><VehicleTypeIcon vehicleType={row.vehicle_type} className="size-5"/></span><div className="min-w-0"><p className="truncate text-[22px] font-extrabold tracking-tight text-slate-950">{row.plate_snapshot}</p><p className="mt-0.5 break-words text-[11px] text-slate-500">{formatVehicleType(row.vehicle_type)} • {row.parking_units?.name??"Unidade não informada"}</p></div></div><div className="flex flex-wrap gap-1.5">{isFinalized?<span className="inline-flex items-center gap-1 rounded-lg bg-emerald-50 px-2 py-1 text-[11px] font-bold text-emerald-700"><ShieldCheck className="size-3"/>Finalizado</span>:null}{isPaid?<span className="inline-flex items-center gap-1 rounded-lg bg-emerald-50 px-2 py-1 text-[11px] font-bold text-emerald-700"><CircleDollarSign className="size-3"/>Pago</span>:null}</div></div></div>
    <DetailSection title="Sessão" icon={Clock3}><div className="grid gap-3 sm:grid-cols-2"><DetailItem icon={CalendarDays} label="Entrada" value={formatDateTime(row.entered_at,tz)}/><DetailItem icon={CalendarDays} label="Saída" value={row.exited_at?formatDateTime(row.exited_at,tz):"—"}/><DetailItem icon={Clock3} label="Permanência" value={formatDuration(duration)}/><DetailItem icon={Layers3} label="Versão" value={String(row.tariff_snapshot?.version_number??"—")}/><DetailItem icon={Tag} label="Tarifa aplicada" value={row.tariff_snapshot?.name??"—"} wide/></div></DetailSection>
    <DetailSection title="Financeiro" icon={CircleDollarSign} tone="green"><div className="grid gap-3 sm:grid-cols-2"><DetailItem icon={WalletCards} label="Valor calculado" value={formatMoney(row.calculated_amount)}/><DetailItem icon={CircleDollarSign} label="Valor final" value={formatMoney(row.final_amount)}/><DetailItem icon={WalletCards} label="Forma/modalidade" value={monthly?"Mensalidade":payment?formatPaymentMethod(payment.method,payment.manual_confirmation):"—"}/><DetailItem icon={CalendarDays} label="Pago em" value={monthly?"Não se aplica":payment?.paid_at?formatDateTime(payment.paid_at,tz):"—"}/></div></DetailSection>
    <DetailSection title="Operação" icon={UserRound}><div className="grid gap-3 sm:grid-cols-2"><DetailItem icon={UserRound} label="Entrada registrada por" value={entryName}/><DetailItem icon={ShieldCheck} label="Saída autorizada por" value={exitName}/></div></DetailSection>
    <section className="mt-2.5 rounded-2xl border border-slate-200 bg-white p-3"><div className="flex items-center gap-2 font-bold text-slate-900"><ShieldCheck className="size-4.5 text-emerald-600"/>Diagnóstico</div><div className={`mt-2.5 rounded-xl border px-3 py-2.5 text-[13px] font-semibold leading-5 ${diagnostic.tone==="success"?"border-emerald-200 bg-emerald-50 text-emerald-800":"border-amber-200 bg-amber-50 text-amber-800"}`}>{diagnostic.text}</div></section>
    <details className="group mt-2.5 overflow-hidden rounded-xl border border-slate-200 bg-white text-xs text-slate-600 shadow-sm"><summary className="flex cursor-pointer list-none items-center justify-between gap-3 px-3.5 py-3 font-semibold text-slate-700 transition hover:bg-slate-50 [&::-webkit-details-marker]:hidden"><span className="flex items-center gap-2"><span className="grid size-7 place-items-center rounded-lg bg-slate-100 text-slate-500">ID</span>Mais detalhes técnicos</span><ChevronDown className="size-4 text-slate-400 transition-transform group-open:rotate-180"/></summary><div className="border-t border-slate-100 bg-slate-50/70 px-3.5 py-3"><div className="grid gap-2"><p><span className="text-slate-400">Situação financeira:</span> <b>{financialLabel}</b></p><p><span className="text-slate-400">Status interno da sessão:</span> <b>{row.status}</b></p><p><span className="text-slate-400">Status interno do pagamento:</span> <b>{row.payment_status}</b></p><p><span className="text-slate-400">ID da sessão:</span> <span className="break-all font-mono text-[11px]">{row.id}</span></p></div></div></details>
  </div>
}

function DetailSection({title,icon:Icon,tone="blue",children}:{title:string;icon:typeof Clock3;tone?:"blue"|"green";children:React.ReactNode}){return <section className={`mt-2.5 rounded-2xl border p-3 ${tone==="green"?"border-emerald-200 bg-emerald-50/50":"border-slate-200 bg-white"}`}><div className="flex items-center gap-2 border-b border-slate-200/80 pb-2.5 font-bold text-slate-900"><Icon className={`size-4.5 ${tone==="green"?"text-emerald-600":"text-blue-600"}`}/>{title}</div><div className="mt-3">{children}</div></section>}
function DetailItem({icon:Icon,label,value,wide=false}:{icon:typeof Clock3;label:string;value:string;wide?:boolean}){return <div className={`flex gap-2.5 ${wide?"sm:col-span-2":""}`}><Icon className="mt-0.5 size-3.5 shrink-0 text-blue-500"/><div className="min-w-0"><p className="text-[10px] text-slate-500">{label}</p><p className="mt-0.5 break-words text-[13px] font-semibold leading-5 text-slate-950">{value}</p></div></div>}
