"use server";

import { revalidatePath } from "next/cache";
import { requireArea } from "@/lib/auth";
import { createClient } from "@/lib/supabase/server";

export type TariffActionState = { error?:string; success?:string; preview?:Array<{minutes:number;total:number}> };
const samples=[10,30,60,90,120,300,600];

function numberFrom(formData:FormData,name:string){return Number(String(formData.get(name)??"").replace(",","."));}
function values(formData:FormData){return {unitId:String(formData.get("unitId")??""),vehicleType:String(formData.get("vehicleType")??""),firstHour:numberFrom(formData,"firstHour"),additional:numberFrom(formData,"additional"),fractionMinutes:numberFrom(formData,"fractionMinutes"),toleranceMinutes:numberFrom(formData,"toleranceMinutes"),dailyAmount:numberFrom(formData,"dailyAmount"),dailyHours:numberFrom(formData,"dailyHours")};}
async function authorizeOwner(unitId:string){const access=await requireArea("ceo");if(!access.assignments.some((item)=>item.unit_id===unitId&&item.role==="owner"))throw new Error("OWNER_FORBIDDEN");}
function validate(input:ReturnType<typeof values>){if(!input.unitId||!["CAR","MOTORCYCLE"].includes(input.vehicleType))return "Selecione uma unidade e um tipo de veículo.";if(!Number.isFinite(input.firstHour)||input.firstHour<=0||!Number.isFinite(input.additional)||input.additional<=0||!Number.isInteger(input.fractionMinutes)||input.fractionMinutes<=0||!Number.isInteger(input.toleranceMinutes)||input.toleranceMinutes<0||!Number.isFinite(input.dailyAmount)||input.dailyAmount<=0||!Number.isInteger(input.dailyHours)||input.dailyHours<=0)return "Revise os valores. Campos monetários devem ser positivos; fração e horas devem ser inteiros positivos; tolerância não pode ser negativa.";return null;}
function message(error:string){if(error.includes("OWNER_FORBIDDEN"))return "Somente o proprietário autorizado desta unidade pode criar tarifas.";if(error.includes("INVALID_TARIFF"))return "Os valores informados não formam uma tarifa válida.";return "Não foi possível processar a tarifa. Tente novamente.";}

export async function previewTariff(_:TariffActionState,formData:FormData):Promise<TariffActionState>{const input=values(formData);const invalid=validate(input);if(invalid)return{error:invalid};try{await authorizeOwner(input.unitId);const supabase=await createClient();const{data,error}=await supabase.rpc("preview_tariff_charges",{target_unit:input.unitId,first_hour:input.firstHour,additional:input.additional,fraction_minutes:input.fractionMinutes,tolerance_minutes:input.toleranceMinutes,daily_amount:input.dailyAmount,daily_hours:input.dailyHours,sample_minutes:samples});if(error)return{error:message(error.message)};return{success:"Simulação calculada pelo motor oficial.",preview:(data??[]) as Array<{minutes:number;total:number}>};}catch(error){return{error:message(error instanceof Error?error.message:"")};}}

export async function createTariffVersion(_:TariffActionState,formData:FormData):Promise<TariffActionState>{const input=values(formData);const invalid=validate(input);if(invalid)return{error:invalid};try{await authorizeOwner(input.unitId);const supabase=await createClient();const{data:current}=await supabase.from("tariff_rules").select("first_hour_amount,additional_amount,additional_fraction_minutes,grace_minutes,daily_cap_amount,daily_after_minutes").eq("unit_id",input.unitId).eq("vehicle_type",input.vehicleType).eq("is_active",true).is("valid_until",null).maybeSingle();if(current&&Number(current.first_hour_amount)===input.firstHour&&Number(current.additional_amount)===input.additional&&current.additional_fraction_minutes===input.fractionMinutes&&current.grace_minutes===input.toleranceMinutes&&Number(current.daily_cap_amount)===input.dailyAmount&&current.daily_after_minutes===input.dailyHours*60)return{error:"Os valores são idênticos à tarifa ativa. Nenhuma nova versão foi criada."};const{error}=await supabase.rpc("create_tariff_version",{target_unit:input.unitId,target_vehicle_type:input.vehicleType,first_hour:input.firstHour,additional:input.additional,fraction_minutes:input.fractionMinutes,tolerance_minutes:input.toleranceMinutes,daily_amount:input.dailyAmount,daily_hours:input.dailyHours});if(error)return{error:message(error.message)};revalidatePath("/ceo/tarifas");revalidatePath("/frentista");revalidatePath("/frentista/entradas");return{success:"Nova versão criada. Ela valerá apenas para novas entradas."};}catch(error){return{error:message(error instanceof Error?error.message:"")};}}

