import { redirect } from "next/navigation";
import { DashboardShell } from "@/components/dashboard-shell";
import { requireArea } from "@/lib/auth";
import { ceoNav } from "@/lib/ceo-nav";
import { formatDateTime,formatMoney } from "@/lib/operator-format";
import { createClient } from "@/lib/supabase/server";
import { TariffForm } from "./tariff-form";

export const dynamic="force-dynamic";
type Tariff={id:string;unit_id:string;name:string;vehicle_type:"CAR"|"MOTORCYCLE";version_number:number;first_hour_amount:number;additional_amount:number;additional_fraction_minutes:number;grace_minutes:number;daily_cap_amount:number;daily_after_minutes:number;valid_from:string;valid_until:string|null;is_active:boolean;parking_units:{name:string;timezone:string}|null};
const typeLabel={CAR:"Carro",MOTORCYCLE:"Moto"};

export default async function TariffsPage(){const access=await requireArea("ceo");const unitIds=[...new Set(access.assignments.filter(item=>item.role==="owner").map(item=>item.unit_id as string))];if(!unitIds.length)redirect("/ceo?erro=sem-permissao");const supabase=await createClient();const[{data:units},{data}]=await Promise.all([supabase.from("parking_units").select("id,name").in("id",unitIds).eq("is_active",true).order("name"),supabase.from("tariff_rules").select("id,unit_id,name,vehicle_type,version_number,first_hour_amount,additional_amount,additional_fraction_minutes,grace_minutes,daily_cap_amount,daily_after_minutes,valid_from,valid_until,is_active,parking_units(name,timezone)").in("unit_id",unitIds).order("valid_from",{ascending:false})]);const tariffs=(data??[]) as unknown as Tariff[];const active=tariffs.filter(item=>item.is_active&&!item.valid_until);return <DashboardShell nav={ceoNav} active="Tarifas" role="CEO"><div className="mx-auto max-w-7xl space-y-6"><div><h1 className="text-3xl font-bold">Tarifas</h1><p className="text-sm text-slate-500">Gerencie os valores cobrados por unidade e tipo de veículo.</p></div><section className="grid gap-4 md:grid-cols-2">{active.map(item=><TariffCard key={item.id} tariff={item}/>)}</section><TariffForm units={units??[]}/><section className="overflow-x-auto rounded-2xl border bg-white"><div className="border-b p-5"><h2 className="text-xl font-bold">Histórico de tarifas</h2><p className="text-sm text-slate-500">Somente leitura. Versões utilizadas por estadias nunca são apagadas.</p></div><table className="w-full min-w-[980px] text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr><th className="p-4">Unidade</th><th>Tipo</th><th>Versão</th><th>Vigência</th><th>Primeira hora</th><th>Fração</th><th>Diária</th><th>Status</th></tr></thead><tbody>{tariffs.map(item=><tr key={item.id} className="border-t"><td className="p-4 font-semibold">{item.parking_units?.name}</td><td>{typeLabel[item.vehicle_type]}</td><td>v{item.version_number}</td><td>{formatDateTime(item.valid_from,item.parking_units?.timezone)}{item.valid_until&&<> — {formatDateTime(item.valid_until,item.parking_units?.timezone)}</>}</td><td>{formatMoney(item.first_hour_amount)}</td><td>{formatMoney(item.additional_amount)} / {item.additional_fraction_minutes} min</td><td>{formatMoney(item.daily_cap_amount)} após {item.daily_after_minutes/60}h</td><td><span className={`rounded-full px-2 py-1 text-xs font-bold ${item.is_active&&!item.valid_until?"bg-emerald-50 text-emerald-700":"bg-slate-100 text-slate-600"}`}>{item.is_active&&!item.valid_until?"Ativa":"Encerrada"}</span></td></tr>)}</tbody></table></section></div></DashboardShell>}
function TariffCard({tariff}:{tariff:Tariff}){return <article className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold uppercase text-blue-600">{tariff.parking_units?.name}</p><h2 className="text-xl font-bold">{typeLabel[tariff.vehicle_type]}</h2></div><span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-700">Ativa · v{tariff.version_number}</span></div><dl className="mt-5 grid grid-cols-2 gap-4 text-sm"><Item label="Primeira hora" value={formatMoney(tariff.first_hour_amount)}/><Item label="Fração adicional" value={`${formatMoney(tariff.additional_amount)} / ${tariff.additional_fraction_minutes} min`}/><Item label="Tolerância" value={`${tariff.grace_minutes} min`}/><Item label="Diária" value={formatMoney(tariff.daily_cap_amount)}/><Item label="Aplicar diária" value={`Após ${tariff.daily_after_minutes/60} horas`}/><Item label="Início" value={formatDateTime(tariff.valid_from,tariff.parking_units?.timezone)}/></dl></article>}
function Item({label,value}:{label:string;value:string}){return <div><dt className="text-xs text-slate-500">{label}</dt><dd className="mt-1 font-semibold">{value}</dd></div>}
