/* Request-scoped Server Components intentionally evaluate elapsed time. */
/* eslint-disable react-hooks/purity */
import Link from "next/link";
import { CarFront, CreditCard, ShieldCheck, UserRound, WalletCards } from "lucide-react";
import { CustomerShell } from "@/components/customer-shell";
import { getCustomerData } from "@/lib/customer-data";
import { formatDateTime, formatDuration, formatMoney, formatParkingStatus, formatVehicleType } from "@/lib/operator-format";

export const dynamic="force-dynamic";
const shortcuts=[{title:"Estadias",text:"Consulte seu histórico",href:"/cliente/estadias",icon:CarFront},{title:"Veículos",text:"Veja os veículos vinculados",href:"/cliente/veiculos",icon:WalletCards},{title:"Pagamentos",text:"Acesse pagamentos e recibos",href:"/cliente/pagamentos",icon:CreditCard},{title:"Minha conta",text:"Dados e segurança",href:"/cliente/conta",icon:UserRound}];
export default async function Page(){const data=await getCustomerData();const firstName=data.profile.full_name.trim().split(/\s+/)[0]||"Cliente";return <CustomerShell name={data.profile.full_name} active="Início"><div className="space-y-6"><div><p className="text-sm font-semibold text-blue-600">Olá, {firstName}</p><h1 className="mt-1 text-2xl font-bold sm:text-3xl">Sua estadia, sem complicação</h1><p className="mt-1 text-sm text-slate-500">Acompanhe somente informações vinculadas à sua conta.</p></div>{data.active?<ActiveStay data={data}/>:<EmptyStay/>}<section><h2 className="mb-3 text-lg font-bold">Acesso rápido</h2><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{shortcuts.map(({title,text,href,icon:Icon})=><Link key={href} href={href} className="group rounded-2xl border bg-white p-4 shadow-sm transition hover:-translate-y-0.5 hover:border-blue-200"><Icon className="size-5 text-blue-600"/><p className="mt-4 font-bold">{title}</p><p className="mt-1 text-xs text-slate-500">{text}</p></Link>)}</div></section><p className="flex items-center justify-center gap-2 text-xs text-slate-400"><ShieldCheck className="size-4"/>Seus dados são protegidos e somente informações vinculadas à sua conta são exibidas.</p></div></CustomerShell>}
function ActiveStay({data}:{data:Awaited<ReturnType<typeof getCustomerData>>}){const session=data.active!;const charge=data.activeCharge;const timezone=session.parking_units?.timezone??"America/Bahia";const amount=charge?.total??session.final_amount??session.calculated_amount;const duration=charge?.duration_minutes??Math.max(0,Math.round((Date.now()-new Date(session.entered_at).getTime())/60000));return <section className="overflow-hidden rounded-3xl border bg-white shadow-sm"><div className="border-b bg-blue-50/50 p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-wide text-blue-600">Estadia atual</p><h2 className="mt-2 text-3xl font-bold tracking-wide">{session.plate_snapshot}</h2><p className="text-sm text-slate-500">{formatVehicleType(session.vehicle_type)}</p></div><span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-700">{formatParkingStatus(session.status)}</span></div><p className="mt-4 font-semibold">{session.parking_units?.name??"Unidade Star Carvalhos"}</p></div><div className="grid gap-5 p-5 sm:grid-cols-3 sm:p-6"><Info label="Entrada" value={formatDateTime(session.entered_at,timezone)}/><Info label="Permanência" value={formatDuration(duration)}/><Info label="Valor atual" value={amount==null?"Em cálculo":formatMoney(amount)} emphasis/><Info label="Tarifa" value={String(session.tariff_snapshot?.name??charge?.tariff_name??"Tarifa da entrada")}/><Info label="Status do pagamento" value={session.payment_status==="PAID"?"Pagamento confirmado":"Aguardando pagamento"}/></div><div className="border-t px-5 py-4 sm:px-6"><Link href={`/cliente/estadias?session=${session.id}`} className="inline-flex min-h-11 items-center rounded-xl bg-blue-600 px-5 text-sm font-bold text-white">Ver detalhes</Link></div></section>}
function EmptyStay(){return <section className="grid min-h-64 place-items-center rounded-3xl border border-dashed bg-white p-8 text-center"><div><span className="mx-auto grid size-14 place-items-center rounded-full bg-blue-50"><CarFront className="size-7 text-blue-600"/></span><h2 className="mt-4 text-lg font-bold">Nenhuma estadia ativa no momento.</h2><p className="mx-auto mt-2 max-w-xl text-sm leading-6 text-slate-500">Quando um veículo vinculado à sua conta entrar no estacionamento, as informações aparecerão aqui automaticamente.</p></div></section>}
function Info({label,value,emphasis=false}:{label:string;value:string;emphasis?:boolean}){return <div><p className="text-xs text-slate-500">{label}</p><p className={`mt-1 font-bold ${emphasis?"text-xl text-emerald-600":""}`}>{value}</p></div>}

