import Link from "next/link";
import { CarFront, FileText, History, LockKeyhole } from "lucide-react";
import { logout } from "@/app/login/actions";
import { Brand } from "@/components/dashboard-shell";
import { requireArea } from "@/lib/auth";
import { formatDateTime, formatDuration, formatMoney } from "@/lib/operator-format";
import { createClient } from "@/lib/supabase/server";
import { serverNow } from "@/lib/server-time";

export const dynamic="force-dynamic";
type Session={id:string;plate_snapshot:string;status:string;entered_at:string;calculated_amount:number|null;final_amount:number|null;tariff_snapshot:{name?:string}|null;parking_units:{name:string;timezone:string}|null};
export default async function ClientPage(){const access=await requireArea("cliente");const supabase=await createClient();const name=access.profile.full_name;const initials=name.split(" ").slice(0,2).map((part:string)=>part[0]).join("").toUpperCase();const{data:vehicles}=await supabase.from("vehicles").select("id").eq("customer_id",access.user.id);const vehicleIds=(vehicles??[]).map(v=>v.id);let active:Session|null=null;if(vehicleIds.length){const{data}=await supabase.from("parking_sessions").select("id,plate_snapshot,status,entered_at,calculated_amount,final_amount,tariff_snapshot,parking_units(name,timezone)").in("vehicle_id",vehicleIds).in("status",["OPEN","PAYMENT_PENDING","PAID","MANUAL_REVIEW"]).order("entered_at",{ascending:false}).limit(1).maybeSingle();active=data as unknown as Session|null}return <main className="min-h-screen bg-slate-100 px-3 py-4 sm:py-8"><div className="mx-auto max-w-[600px] overflow-hidden rounded-[28px] border bg-white shadow-2xl"><header className="flex h-20 items-center justify-between border-b px-6"><Brand href="/cliente"/><form action={logout}><button className="rounded-xl border px-3 py-2 text-xs font-semibold">Sair</button></form></header><div className="flex items-center gap-3 border-b px-5 py-3"><span className="grid size-11 place-items-center rounded-full bg-blue-50 font-bold text-blue-600">{initials}</span><div><p className="text-sm font-semibold">Olá, {name}</p><p className="text-xs text-slate-500">Conta de cliente autenticada</p></div></div><div className="space-y-4 p-5"><div><h1 className="text-2xl font-bold">Painel do Cliente</h1><p className="text-sm text-slate-500">Consulte somente estadias associadas à sua conta.</p></div>{active?<ActiveSession session={active} now={serverNow()}/>:<section className="grid min-h-56 place-items-center rounded-2xl border border-dashed bg-slate-50 p-8 text-center"><div><CarFront className="mx-auto size-10 text-slate-400"/><h2 className="mt-4 font-bold">Você não possui um veículo estacionado no momento.</h2><p className="mt-2 text-sm text-slate-500">Uma estadia só aparece quando o veículo está associado com segurança ao seu cadastro.</p></div></section>}<div className="grid grid-cols-2 gap-3"><Quick href="/cliente/historico" icon={History} title="Histórico" text="Ver estadias reais"/><Quick href="/cliente/recibos" icon={FileText} title="Recibos" text="Pagamentos confirmados"/></div><p className="flex items-center justify-center gap-2 py-2 text-[11px] text-slate-400"><LockKeyhole className="size-3"/>Seus dados são protegidos por controle de acesso.</p></div></div></main>}
function ActiveSession({session,now}:{session:Session;now:number}){const tz=session.parking_units?.timezone??"America/Bahia";const minutes=Math.max(0,Math.round((now-new Date(session.entered_at).getTime())/60000));return <section className="rounded-2xl border p-5"><div className="flex justify-between"><div><p className="text-xs text-slate-500">Placa</p><h2 className="text-2xl font-bold">{session.plate_snapshot}</h2></div><span className="h-fit rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-700">{session.status}</span></div><dl className="mt-5 grid grid-cols-2 gap-4 text-sm"><div><dt className="text-slate-500">Entrada</dt><dd className="font-semibold">{formatDateTime(session.entered_at,tz)}</dd></div><div><dt className="text-slate-500">Permanência</dt><dd className="font-semibold">{formatDuration(minutes)}</dd></div><div><dt className="text-slate-500">Tarifa</dt><dd className="font-semibold">{session.tariff_snapshot?.name??"—"}</dd></div><div><dt className="text-slate-500">Valor atual</dt><dd className="font-semibold">{formatMoney(session.final_amount??session.calculated_amount)}</dd></div></dl><p className="mt-5 rounded-xl bg-slate-50 p-3 text-xs text-slate-500">PIX ainda não está disponível. Nenhum QR Code ou pagamento fictício é exibido.</p></section>}
function Quick({href,icon:Icon,title,text}:{href:string;icon:typeof History;title:string;text:string}){return <Link href={href} className="flex items-center gap-3 rounded-xl border p-4 hover:bg-blue-50"><Icon className="size-5 text-blue-600"/><span><b className="block text-sm">{title}</b><small className="text-slate-500">{text}</small></span></Link>}

