Exit code: 0
Wall time: 0.9 seconds
Output:
import Link from "next/link";
import { CarFront,CheckCircle2,ChevronDown,CircleHelp,Clock3,CreditCard,FileText,History,LockKeyhole,MapPin,QrCode,RefreshCw,Tag } from "lucide-react";
import { Brand,DemoNotice } from "@/components/dashboard-shell";
import { ActionButton } from "@/components/action-button";
import { logout } from "@/app/login/actions";
import { PixActions } from "@/components/pix-actions";
import { getAccess } from "@/lib/auth";
export default async function ClientPage(){const access=await getAccess();const name=access?.profile.full_name??"Cliente";const initials=name.split(" ").slice(0,2).map((part: string)=>part[0]).join("").toUpperCase();return <main className="min-h-screen bg-slate-100 px-3 py-4 sm:py-8"><div className="mx-auto max-w-[600px] overflow-hidden rounded-[28px] border bg-white shadow-2xl"><header className="flex h-20 items-center justify-between border-b px-6"><Brand href="/cliente"/><form action={logout}><button className="rounded-xl border px-3 py-2 text-xs font-semibold text-slate-600 hover:bg-slate-50">Sair</button></form></header><div className="flex items-center gap-3 border-b px-5 py-3"><span className="grid size-11 place-items-center rounded-full bg-blue-50 font-bold text-blue-600">{initials}</span><div className="flex-1"><p className="text-sm font-semibold">Olá, {name}</p><p className="text-xs text-slate-500">Cliente desde jan/2024</p></div><ChevronDown className="size-4"/></div><div className="space-y-3 p-4 sm:p-5"><div className="flex items-end justify-between"><div><h1 className="text-2xl font-bold">Painel do Cliente</h1><p className="text-sm text-slate-500">Acompanhe e pague seu estacionamento.</p></div><DemoNotice/></div>
<section className="rounded-2xl border p-4 shadow-sm"><div className="flex items-start justify-between"><div className="flex gap-3"><span className="grid size-12 place-items-center rounded-2xl bg-blue-50 text-blue-600"><CarFront/></span><div><p className="text-xs text-slate-500">Placa</p><p className="text-2xl font-bold">ABC1D23</p></div></div><span className="rounded-lg bg-emerald-50 px-3 py-2 text-xs font-semibold text-emerald-700">&bull; Estacionado agora</span></div><div className="my-4 grid grid-cols-3 divide-x border-y py-3"><Info icon={Clock3} label="Entrada" value="Hoje 08:15"/><Info icon={CheckCircle2} label="Tempo" value="2h 35m"/><Info icon={Tag} label="Tarifa" value="R$ 6,00/h"/></div><div className="flex items-center justify-between"><div><p className="text-xs text-slate-500">Valor atual</p><p className="text-2xl font-bold text-emerald-600">R$ 12,00</p></div><div className="rounded-xl bg-emerald-50 px-4 py-3 text-xs text-emerald-700">At&eacute; 30min ap&oacute;s a sa&iacute;da<br/>para pagar sem multa.</div></div>
<div className="mt-4 grid gap-4 rounded-2xl border bg-slate-50 p-3 sm:grid-cols-[160px_1fr]"><div className="grid aspect-square place-items-center rounded-xl border bg-white"><div className="qr-demo grid size-[130px] place-items-center"><QrCode className="size-11 rounded-xl bg-white p-2 text-emerald-600"/></div></div><div className="flex flex-col justify-center"><p className="flex items-center gap-2 font-bold"><span className="grid size-9 place-items-center rounded-xl bg-emerald-500 text-white"><CreditCard className="size-5"/></span>Pagar com PIX</p><p className="mt-1 text-xs text-slate-500">Escaneie o QR Code com seu banco</p><PixActions/></div></div></section>
<div className="grid grid-cols-2 gap-3"><Quick icon={RefreshCw} title="Atualizar status" text="Atualiza&ccedil;&atilde;o: 08:50"/><Quick href="/cliente/ajuda" icon={CircleHelp} title="Precisa de ajuda?" text="Falar com suporte"/></div><section className="rounded-2xl border p-4"><p className="text-sm font-semibold">Status do pagamento</p><div className="mt-4 grid grid-cols-3 text-center text-xs"><Step icon={Clock3} title="Aguardando pagamento" active/><Step icon={CheckCircle2} title="Pagamento confirmado"/><Step icon={CarFront} title="Saída liberada"/></div></section><section className="flex items-center gap-3 rounded-2xl border border-blue-300 bg-blue-50/50 p-4"><span className="grid size-12 place-items-center rounded-full bg-blue-600 text-xl font-bold text-white">S</span><div className="flex-1"><p className="text-sm font-bold">Star Carvalhos Central</p><p className="text-xs text-slate-500">Janela de sa&iacute;da: 08:15 at&eacute; 09:15</p></div><MapPin className="size-5 text-blue-600"/></section><div className="grid grid-cols-3 gap-3"><Quick href="/cliente/historico" icon={History} title="Hist&oacute;rico" text="Ver estadias"/><Quick href="/cliente/recibos" icon={FileText} title="Recibos" text="Comprovantes"/><Quick href="/cliente/saida" icon={CarFront} title="Saída" text="Como funciona"/></div><p className="flex items-center justify-center gap-2 py-2 text-[11px] text-slate-400"><LockKeyhole className="size-3"/>Pagamento seguro com PIX.</p></div></div></main>}
function Info({icon:Icon,label,value}:{icon:typeof Clock3;label:string;value:string}){return <div className="flex items-center justify-center gap-2 px-1"><Icon className="size-5 text-blue-600"/><div><p className="text-[10px] text-slate-500">{label}</p><p className="text-xs font-semibold">{value}</p></div></div>}
function Quick({icon:Icon,title,text,href}:{icon:typeof Clock3;title:string;text:string;href?:string}){const content=<><Icon className="size-5 text-blue-600"/><span><b className="block text-xs text-blue-600">{title}</b><small className="text-[10px] text-slate-500">{text}</small></span></>;return href?<Link href={href} className="flex items-center gap-2 rounded-xl border p-3 text-left transition hover:bg-blue-50">{content}</Link>:<ActionButton className="flex items-center gap-2 rounded-xl border p-3 text-left">{content}</ActionButton>}
function Step({icon:Icon,title,active=false}:{icon:typeof Clock3;title:string;active?:boolean}){return <div className={active?"text-blue-600":"text-slate-400"}><span className="mx-auto grid size-9 place-items-center rounded-full border-2 bg-white"><Icon className="size-4"/></span><p className="mt-2 px-1">{title}</p></div>}













